### ISSUE TITLE
Getting non-expected values after compiling for x64 (MinGW)

### ISSUE THREAD

**Issue by IgorJorobus** [matthieu-labas/sxmlc#10]
Hello Matthieu,

I keep on using this lib. I compiled the code with MinGW x64 and found out that i.e.: `node->n_children` misleads the actual value of children number, it usually returns a very high number, i.e.: **108708416**. Worth to mention that with MinGW x86 works perfect.

**Comment by IgorJorobus** [comment]
Please, disregard this, after a lot of debugging, I realized it's my code.

**Comment by matthieu-labas** [comment]
Yes it happens when you don't call `XMLNode_init()`.

**Comment by embbo** [comment]
#include <stdio.h>
#include <stdlib.h>
#include "sxmlc.h"
#include "sxmlsearch.h"

const char *buffer = "<?xml version='1.0' encoding='utf-8'?>\n"
"<UANodeSet xmlns=\"http://opcfoundation.org/UA/2011/03/UANodeSet.xsd\" xmlns:uax=\"http://opcfoundation.org/UA/2008/02/Types.xsd\" xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\" xmlns:xsi=\"http://www.w3.org/2001/XMLSchema-instance\">\n"
"  <NamespaceUris>\n"
"    <Uri>urx:reoag:mytestproject</Uri>\n"
"  </NamespaceUris>\n"
"  <Aliases>\n"
"    <Alias Alias=\"Int32\">i=6</Alias>\n"
"    <Alias Alias=\"Float\">i=10</Alias>\n"
"    <Alias Alias=\"String\">i=12</Alias>\n"
"    <Alias Alias=\"Organizes\">i=35</Alias>\n"
"    <Alias Alias=\"HasTypeDefinition\">i=40</Alias>\n"
"    <Alias Alias=\"HasSubtype\">i=45</Alias>\n"
"    <Alias Alias=\"HasProperty\">i=46</Alias>\n"
"    <Alias Alias=\"HasComponent\">i=47</Alias>\n"
"    <Alias Alias=\"Argument\">i=296</Alias>\n"
"  </Aliases>\n"
"  <UAObjectType BrowseName=\"MyDeviceBrowseName\" NodeId=\"ns=1;i=2001\">\n"
"    <DisplayName>MyDeviceDisplayName</DisplayName>\n"
"    <Description>MyDeviceDescription</Description>\n"
"    <References>\n"
"      <Reference IsForward=\"false\" ReferenceType=\"HasSubtype\">i=58</Reference>\n"
"      <Reference ReferenceType=\"HasComponent\">ns=1;i=2005</Reference>\n"
"    </References>\n"
"  </UAObjectType>\n"
"  <UAVariable BrowseName=\"1:DeviceNameBrowseName\" DataType=\"String\" NodeId=\"ns=1;i=2005\" ParentNodeId=\"ns=1;i=2001\">\n"
"    <DisplayName>DeviceName</DisplayName>\n"
"    <Description IsEnable=\"false\" >DeviceDescription</Description>\n"
"    <References>\n"
"      <Reference IsForward=\"false\" ReferenceType=\"HasComponent\">ns=1;i=2001</Reference>\n"
"      <Reference ReferenceType=\"HasTypeDefinition\">i=63</Reference>\n"
"    </References>\n"
"    <Value>\n"
"      <uax:String>MyName</uax:String>\n"
"    </Value>\n"
"  </UAVariable>\n"
"  <UAObject BrowseName=\"1:REOVIB\" NodeId=\"i=99999\" ParentNodeId=\"i=85\">\n"
"    <DisplayName>REOVIB</DisplayName>\n"
"    <References>\n"
"      <Reference IsForward=\"false\" ReferenceType=\"Organizes\">i=85</Reference>\n"
"      <Reference ReferenceType=\"HasTypeDefinition\">i=58</Reference>\n"
"      <Reference ReferenceType=\"HasComponent\">i=66666</Reference>\n"
"      <Reference ReferenceType=\"HasComponent\">i=77777</Reference>\n"
"      <Reference ReferenceType=\"HasComponent\">i=509000</Reference>\n"
"    </References>\n"
"  </UAObject>\n"
"  <UAVariable AccessLevel=\"3\" BrowseName=\"1:minAccel\" DataType=\"Float\" NodeId=\"i=66666\" ParentNodeId=\"i=99999\" UserAccessLevel=\"3\">\n"
"    <DisplayName>DisplayNameminAccel</DisplayName>\n"
"    <Description>DescriptionminAccel</Description>\n"
"    <References>\n"
"      <Reference IsForward=\"false\" ReferenceType=\"HasComponent\">i=99999</Reference>\n"
"      <Reference ReferenceType=\"HasTypeDefinition\">i=63</Reference>\n"
"      <Reference ReferenceType=\"HasComponent\">i=66661</Reference>\n"
"    </References>\n"
"    <Value>\n"
"      <uax:Float>0.0</uax:Float>\n"
"    </Value>\n"
"  </UAVariable>\n"
"  <UAVariable BrowseName=\"1:CanAdress\" DataType=\"Int32\" NodeId=\"i=66661\" ParentNodeId=\"i=66666\">\n"
"    <DisplayName>CanAdress</DisplayName>\n"
"    <Description>CanAdressminAccel</Description>\n"
"    <References>\n"
"      <Reference IsForward=\"false\" ReferenceType=\"HasComponent\">i=66666</Reference>\n"
"      <Reference ReferenceType=\"HasTypeDefinition\">i=63</Reference>\n"
"    </References>\n"
"    <Value>\n"
"      <uax:Int32>16000</uax:Int32>\n"
"    </Value>\n"
"  </UAVariable>\n"
"  <UAVariable BrowseName=\"1:minBel\" DataType=\"Float\" NodeId=\"i=77777\" ParentNodeId=\"i=99999\">\n"
"    <DisplayName>minBel</DisplayName>\n"
"    <Description>minBel</Description>\n"
"    <References>\n"
"      <Reference IsForward=\"false\" ReferenceType=\"HasComponent\">i=99999</Reference>\n"
"      <Reference ReferenceType=\"HasTypeDefinition\">i=63</Reference>\n"
"      <Reference ReferenceType=\"HasComponent\">i=77771</Reference>\n"
"    </References>\n"
"    <Value>\n"
"      <uax:Float>0.0</uax:Float>\n"
"    </Value>\n"
"  </UAVariable>\n"
"  <UAVariable BrowseName=\"1:AdressMinBel\" DataType=\"Int32\" NodeId=\"i=77771\" ParentNodeId=\"i=77777\">\n"
"    <DisplayName>AdressMinBel</DisplayName>\n"
"    <Description>AdressMinBel</Description>\n"
"    <References>\n"
"      <Reference IsForward=\"false\" ReferenceType=\"HasComponent\">i=77777</Reference>\n"
"      <Reference ReferenceType=\"HasTypeDefinition\">i=63</Reference>\n"
"    </References>\n"
"    <Value>\n"
"      <uax:Int32>102200</uax:Int32>\n"
"    </Value>\n"
"  </UAVariable>\n"
"  <UAMethod BrowseName=\"1:Certificate\" NodeId=\"i=509000\" ParentNodeId=\"i=99999\">\n"
"    <DisplayName>CertificateDisplayName</DisplayName>\n"
"    <Description>CertificateDescription</Description>\n"
"    <References>\n"
"      <Reference IsForward=\"false\" ReferenceType=\"HasComponent\">i=99999</Reference>\n"
"      <Reference ReferenceType=\"HasProperty\">i=20001</Reference>\n"
"      <Reference ReferenceType=\"HasProperty\">i=20002</Reference>\n"
"    </References>\n"
"  </UAMethod>\n"
"  <UAVariable BrowseName=\"0:InputArguments\" DataType=\"Argument\" NodeId=\"i=20001\" ParentNodeId=\"i=509000\" ValueRank=\"0\">\n"
"    <DisplayName>InputArguments</DisplayName>\n"
"    <Description>InputArguments</Description>\n"
"    <References>\n"
"      <Reference IsForward=\"false\" ReferenceType=\"HasProperty\">i=509000</Reference>\n"
"      <Reference ReferenceType=\"HasTypeDefinition\">i=68</Reference>\n"
"    </References>\n"
"    <Value>\n"
"      <uax:ListOfExtensionObject>\n"
"        <uax:ExtensionObject>\n"
"          <uax:TypeId>\n"
"            <uax:Identifier>i=296</uax:Identifier>\n"
"          </uax:TypeId>\n"
"          <uax:Body>\n"
"            <uax:Argument>\n"
"              <uax:Name>InputArgu</uax:Name>\n"
"              <uax:DataType>\n"
"                <uax:Identifier>i=6</uax:Identifier>\n"
"              </uax:DataType>\n"
"              <uax:ValueRank>-1</uax:ValueRank>\n"
"              <uax:ArrayDimensions />\n"
"              <uax:Description>\n"
"                <uax:Encoding>2</uax:Encoding>\n"
"                <uax:Locale />\n"
"                <uax:Text>You can upload </uax:Text>\n"
"              </uax:Description>\n"
"            </uax:Argument>\n"
"          </uax:Body>\n"
"        </uax:ExtensionObject>\n"
"      </uax:ListOfExtensionObject>\n"
"    </Value>\n"
"  </UAVariable>\n"
"  <UAVariable BrowseName=\"0:OutputArguments\" DataType=\"Argument\" NodeId=\"i=20002\" ParentNodeId=\"i=509000\" ValueRank=\"0\">\n"
"    <DisplayName>OutputArguments</DisplayName>\n"
"    <Description>OutputArguments</Description>\n"
"    <References>\n"
"      <Reference IsForward=\"false\" ReferenceType=\"HasProperty\">i=509000</Reference>\n"
"      <Reference ReferenceType=\"HasTypeDefinition\">i=68</Reference>\n"
"    </References>\n"
"    <Value>\n"
"      <uax:ListOfExtensionObject>\n"
"        <uax:ExtensionObject>\n"
"          <uax:TypeId>\n"
"            <uax:Identifier>i=296</uax:Identifier>\n"
"          </uax:TypeId>\n"
"          <uax:Body>\n"
"            <uax:Argument>\n"
"              <uax:Name>OutPutArgu</uax:Name>\n"
"              <uax:DataType>\n"
"                <uax:Identifier>i=12</uax:Identifier>\n"
"              </uax:DataType>\n"
"              <uax:ValueRank>-1</uax:ValueRank>\n"
"              <uax:ArrayDimensions />\n"
"              <uax:Description>\n"
"                <uax:Encoding>2</uax:Encoding>\n"
"                <uax:Locale />\n"
"                <uax:Text>You can see the status</uax:Text>\n"
"              </uax:Description>\n"
"            </uax:Argument>\n"
"          </uax:Body>\n"
"        </uax:ExtensionObject>\n"
"      </uax:ListOfExtensionObject>\n"
"    </Value>\n"
"  </UAVariable>\n"
"</UANodeSet>\n";



int main()
{
XMLNode node;
XMLNode_init(&node);
XMLDoc doc;
XMLDoc_init(&doc);
XMLDoc_parse_buffer_DOM(buffer, "test", &doc);
XMLNode* root = doc.nodes[doc.i_root];
char val[256];
char* p = val;
XMLNode_get_attribute_with_default(&node, "BrowseName", &p, NULL);
if (p == NULL) {
    fprintf(stderr, "BrowseName not found!\n");
} else {
    printf("BrowseName = [%s]\n", val);
}
    return 0;
}

**Comment by embbo** [comment]
`#include <stdio.h>
#include <stdlib.h>
#include "sxmlc.h"
#include "sxmlsearch.h"

const char *buffer = "<?xml version='1.0' encoding='utf-8'?>\n"
"<UANodeSet xmlns=\"http://opcfoundation.org/UA/2011/03/UANodeSet.xsd\" xmlns:uax=\"http://opcfoundation.org/UA/2008/02/Types.xsd\" xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\" xmlns:xsi=\"http://www.w3.org/2001/XMLSchema-instance\">\n"
"  <NamespaceUris>\n"
"    <Uri>urx:reoag:mytestproject</Uri>\n"
"  </NamespaceUris>\n"
"  <Aliases>\n"
"    <Alias Alias=\"Int32\">i=6</Alias>\n"
"    <Alias Alias=\"Float\">i=10</Alias>\n"
"    <Alias Alias=\"String\">i=12</Alias>\n"
"    <Alias Alias=\"Organizes\">i=35</Alias>\n"
"    <Alias Alias=\"HasTypeDefinition\">i=40</Alias>\n"
"    <Alias Alias=\"HasSubtype\">i=45</Alias>\n"
"    <Alias Alias=\"HasProperty\">i=46</Alias>\n"
"    <Alias Alias=\"HasComponent\">i=47</Alias>\n"
"    <Alias Alias=\"Argument\">i=296</Alias>\n"
"  </Aliases>\n"
"  <UAObjectType BrowseName=\"MyDeviceBrowseName\" NodeId=\"ns=1;i=2001\">\n"
"    <DisplayName>MyDeviceDisplayName</DisplayName>\n"
"    <Description>MyDeviceDescription</Description>\n"
"    <References>\n"
"      <Reference IsForward=\"false\" ReferenceType=\"HasSubtype\">i=58</Reference>\n"
"      <Reference ReferenceType=\"HasComponent\">ns=1;i=2005</Reference>\n"
"    </References>\n"
"  </UAObjectType>\n"
"  <UAVariable BrowseName=\"1:DeviceNameBrowseName\" DataType=\"String\" NodeId=\"ns=1;i=2005\" ParentNodeId=\"ns=1;i=2001\">\n"
"    <DisplayName>DeviceName</DisplayName>\n"
"    <Description IsEnable=\"false\" >DeviceDescription</Description>\n"
"    <References>\n"
"      <Reference IsForward=\"false\" ReferenceType=\"HasComponent\">ns=1;i=2001</Reference>\n"
"      <Reference ReferenceType=\"HasTypeDefinition\">i=63</Reference>\n"
"    </References>\n"
"    <Value>\n"
"      <uax:String>MyName</uax:String>\n"
"    </Value>\n"
"  </UAVariable>\n"
"  <UAObject BrowseName=\"1:REOVIB\" NodeId=\"i=99999\" ParentNodeId=\"i=85\">\n"
"    <DisplayName>REOVIB</DisplayName>\n"
"    <References>\n"
"      <Reference IsForward=\"false\" ReferenceType=\"Organizes\">i=85</Reference>\n"
"      <Reference ReferenceType=\"HasTypeDefinition\">i=58</Reference>\n"
"      <Reference ReferenceType=\"HasComponent\">i=66666</Reference>\n"
"      <Reference ReferenceType=\"HasComponent\">i=77777</Reference>\n"
"      <Reference ReferenceType=\"HasComponent\">i=509000</Reference>\n"
"    </References>\n"
"  </UAObject>\n"
"  <UAVariable AccessLevel=\"3\" BrowseName=\"1:minAccel\" DataType=\"Float\" NodeId=\"i=66666\" ParentNodeId=\"i=99999\" UserAccessLevel=\"3\">\n"
"    <DisplayName>DisplayNameminAccel</DisplayName>\n"
"    <Description>DescriptionminAccel</Description>\n"
"    <References>\n"
"      <Reference IsForward=\"false\" ReferenceType=\"HasComponent\">i=99999</Reference>\n"
"      <Reference ReferenceType=\"HasTypeDefinition\">i=63</Reference>\n"
"      <Reference ReferenceType=\"HasComponent\">i=66661</Reference>\n"
"    </References>\n"
"    <Value>\n"
"      <uax:Float>0.0</uax:Float>\n"
"    </Value>\n"
"  </UAVariable>\n"
"  <UAVariable BrowseName=\"1:CanAdress\" DataType=\"Int32\" NodeId=\"i=66661\" ParentNodeId=\"i=66666\">\n"
"    <DisplayName>CanAdress</DisplayName>\n"
"    <Description>CanAdressminAccel</Description>\n"
"    <References>\n"
"      <Reference IsForward=\"false\" ReferenceType=\"HasComponent\">i=66666</Reference>\n"
"      <Reference ReferenceType=\"HasTypeDefinition\">i=63</Reference>\n"
"    </References>\n"
"    <Value>\n"
"      <uax:Int32>16000</uax:Int32>\n"
"    </Value>\n"
"  </UAVariable>\n"
"  <UAVariable BrowseName=\"1:minBel\" DataType=\"Float\" NodeId=\"i=77777\" ParentNodeId=\"i=99999\">\n"
"    <DisplayName>minBel</DisplayName>\n"
"    <Description>minBel</Description>\n"
"    <References>\n"
"      <Reference IsForward=\"false\" ReferenceType=\"HasComponent\">i=99999</Reference>\n"
"      <Reference ReferenceType=\"HasTypeDefinition\">i=63</Reference>\n"
"      <Reference ReferenceType=\"HasComponent\">i=77771</Reference>\n"
"    </References>\n"
"    <Value>\n"
"      <uax:Float>0.0</uax:Float>\n"
"    </Value>\n"
"  </UAVariable>\n"
"  <UAVariable BrowseName=\"1:AdressMinBel\" DataType=\"Int32\" NodeId=\"i=77771\" ParentNodeId=\"i=77777\">\n"
"    <DisplayName>AdressMinBel</DisplayName>\n"
"    <Description>AdressMinBel</Description>\n"
"    <References>\n"
"      <Reference IsForward=\"false\" ReferenceType=\"HasComponent\">i=77777</Reference>\n"
"      <Reference ReferenceType=\"HasTypeDefinition\">i=63</Reference>\n"
"    </References>\n"
"    <Value>\n"
"      <uax:Int32>102200</uax:Int32>\n"
"    </Value>\n"
"  </UAVariable>\n"
"  <UAMethod BrowseName=\"1:Certificate\" NodeId=\"i=509000\" ParentNodeId=\"i=99999\">\n"
"    <DisplayName>CertificateDisplayName</DisplayName>\n"
"    <Description>CertificateDescription</Description>\n"
"    <References>\n"
"      <Reference IsForward=\"false\" ReferenceType=\"HasComponent\">i=99999</Reference>\n"
"      <Reference ReferenceType=\"HasProperty\">i=20001</Reference>\n"
"      <Reference ReferenceType=\"HasProperty\">i=20002</Reference>\n"
"    </References>\n"
"  </UAMethod>\n"
"  <UAVariable BrowseName=\"0:InputArguments\" DataType=\"Argument\" NodeId=\"i=20001\" ParentNodeId=\"i=509000\" ValueRank=\"0\">\n"
"    <DisplayName>InputArguments</DisplayName>\n"
"    <Description>InputArguments</Description>\n"
"    <References>\n"
"      <Reference IsForward=\"false\" ReferenceType=\"HasProperty\">i=509000</Reference>\n"
"      <Reference ReferenceType=\"HasTypeDefinition\">i=68</Reference>\n"
"    </References>\n"
"    <Value>\n"
"      <uax:ListOfExtensionObject>\n"
"        <uax:ExtensionObject>\n"
"          <uax:TypeId>\n"
"            <uax:Identifier>i=296</uax:Identifier>\n"
"          </uax:TypeId>\n"
"          <uax:Body>\n"
"            <uax:Argument>\n"
"              <uax:Name>InputArgu</uax:Name>\n"
"              <uax:DataType>\n"
"                <uax:Identifier>i=6</uax:Identifier>\n"
"              </uax:DataType>\n"
"              <uax:ValueRank>-1</uax:ValueRank>\n"
"              <uax:ArrayDimensions />\n"
"              <uax:Description>\n"
"                <uax:Encoding>2</uax:Encoding>\n"
"                <uax:Locale />\n"
"                <uax:Text>You can upload </uax:Text>\n"
"              </uax:Description>\n"
"            </uax:Argument>\n"
"          </uax:Body>\n"
"        </uax:ExtensionObject>\n"
"      </uax:ListOfExtensionObject>\n"
"    </Value>\n"
"  </UAVariable>\n"
"  <UAVariable BrowseName=\"0:OutputArguments\" DataType=\"Argument\" NodeId=\"i=20002\" ParentNodeId=\"i=509000\" ValueRank=\"0\">\n"
"    <DisplayName>OutputArguments</DisplayName>\n"
"    <Description>OutputArguments</Description>\n"
"    <References>\n"
"      <Reference IsForward=\"false\" ReferenceType=\"HasProperty\">i=509000</Reference>\n"
"      <Reference ReferenceType=\"HasTypeDefinition\">i=68</Reference>\n"
"    </References>\n"
"    <Value>\n"
"      <uax:ListOfExtensionObject>\n"
"        <uax:ExtensionObject>\n"
"          <uax:TypeId>\n"
"            <uax:Identifier>i=296</uax:Identifier>\n"
"          </uax:TypeId>\n"
"          <uax:Body>\n"
"            <uax:Argument>\n"
"              <uax:Name>OutPutArgu</uax:Name>\n"
"              <uax:DataType>\n"
"                <uax:Identifier>i=12</uax:Identifier>\n"
"              </uax:DataType>\n"
"              <uax:ValueRank>-1</uax:ValueRank>\n"
"              <uax:ArrayDimensions />\n"
"              <uax:Description>\n"
"                <uax:Encoding>2</uax:Encoding>\n"
"                <uax:Locale />\n"
"                <uax:Text>You can see the status</uax:Text>\n"
"              </uax:Description>\n"
"            </uax:Argument>\n"
"          </uax:Body>\n"
"        </uax:ExtensionObject>\n"
"      </uax:ListOfExtensionObject>\n"
"    </Value>\n"
"  </UAVariable>\n"
"</UANodeSet>\n";



int main()
{
XMLNode node;
XMLNode_init(&node);
XMLDoc doc;
XMLDoc_init(&doc);
XMLDoc_parse_buffer_DOM(buffer, "test", &doc);
XMLNode* root = doc.nodes[doc.i_root];
char val[256];
char* p = val;
XMLNode_get_attribute_with_default(&node, "BrowseName", &p, NULL);
if (p == NULL) {
    fprintf(stderr, "BrowseName not found!\n");
} else {
    printf("BrowseName = [%s]\n", val);
}
    return 0;
}
`

**Comment by embbo** [comment]
> `#include <stdio.h>
#include <stdlib.h>
#include "sxmlc.h"
#include "sxmlsearch.h"

const char *buffer = "<?xml version='1.0' encoding='utf-8'?>\n"
"<UANodeSet xmlns=\"http://opcfoundation.org/UA/2011/03/UANodeSet.xsd\" xmlns:uax=\"http://opcfoundation.org/UA/2008/02/Types.xsd\" xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\" xmlns:xsi=\"http://www.w3.org/2001/XMLSchema-instance\">\n"
"  <NamespaceUris>\n"
"    <Uri>urx:reoag:mytestproject</Uri>\n"
"  </NamespaceUris>\n"
"  <Aliases>\n"
"    <Alias Alias=\"Int32\">i=6</Alias>\n"
"    <Alias Alias=\"Float\">i=10</Alias>\n"
"    <Alias Alias=\"String\">i=12</Alias>\n"
"    <Alias Alias=\"Organizes\">i=35</Alias>\n"
"    <Alias Alias=\"HasTypeDefinition\">i=40</Alias>\n"
"    <Alias Alias=\"HasSubtype\">i=45</Alias>\n"
"    <Alias Alias=\"HasProperty\">i=46</Alias>\n"
"    <Alias Alias=\"HasComponent\">i=47</Alias>\n"
"    <Alias Alias=\"Argument\">i=296</Alias>\n"
"  </Aliases>\n"
"  <UAObjectType BrowseName=\"MyDeviceBrowseName\" NodeId=\"ns=1;i=2001\">\n"
"    <DisplayName>MyDeviceDisplayName</DisplayName>\n"
"    <Description>MyDeviceDescription</Description>\n"
"    <References>\n"
"      <Reference IsForward=\"false\" ReferenceType=\"HasSubtype\">i=58</Reference>\n"
"      <Reference ReferenceType=\"HasComponent\">ns=1;i=2005</Reference>\n"
"    </References>\n"
"  </UAObjectType>\n"
"  <UAVariable BrowseName=\"1:DeviceNameBrowseName\" DataType=\"String\" NodeId=\"ns=1;i=2005\" ParentNodeId=\"ns=1;i=2001\">\n"
"    <DisplayName>DeviceName</DisplayName>\n"
"    <Description IsEnable=\"false\" >DeviceDescription</Description>\n"
"    <References>\n"
"      <Reference IsForward=\"false\" ReferenceType=\"HasComponent\">ns=1;i=2001</Reference>\n"
"      <Reference ReferenceType=\"HasTypeDefinition\">i=63</Reference>\n"
"    </References>\n"
"    <Value>\n"
"      <uax:String>MyName</uax:String>\n"
"    </Value>\n"
"  </UAVariable>\n"
"  <UAObject BrowseName=\"1:REOVIB\" NodeId=\"i=99999\" ParentNodeId=\"i=85\">\n"
"    <DisplayName>REOVIB</DisplayName>\n"
"    <References>\n"
"      <Reference IsForward=\"false\" ReferenceType=\"Organizes\">i=85</Reference>\n"
"      <Reference ReferenceType=\"HasTypeDefinition\">i=58</Reference>\n"
"      <Reference ReferenceType=\"HasComponent\">i=66666</Reference>\n"
"      <Reference ReferenceType=\"HasComponent\">i=77777</Reference>\n"
"      <Reference ReferenceType=\"HasComponent\">i=509000</Reference>\n"
"    </References>\n"
"  </UAObject>\n"
"  <UAVariable AccessLevel=\"3\" BrowseName=\"1:minAccel\" DataType=\"Float\" NodeId=\"i=66666\" ParentNodeId=\"i=99999\" UserAccessLevel=\"3\">\n"
"    <DisplayName>DisplayNameminAccel</DisplayName>\n"
"    <Description>DescriptionminAccel</Description>\n"
"    <References>\n"
"      <Reference IsForward=\"false\" ReferenceType=\"HasComponent\">i=99999</Reference>\n"
"      <Reference ReferenceType=\"HasTypeDefinition\">i=63</Reference>\n"
"      <Reference ReferenceType=\"HasComponent\">i=66661</Reference>\n"
"    </References>\n"
"    <Value>\n"
"      <uax:Float>0.0</uax:Float>\n"
"    </Value>\n"
"  </UAVariable>\n"
"  <UAVariable BrowseName=\"1:CanAdress\" DataType=\"Int32\" NodeId=\"i=66661\" ParentNodeId=\"i=66666\">\n"
"    <DisplayName>CanAdress</DisplayName>\n"
"    <Description>CanAdressminAccel</Description>\n"
"    <References>\n"
"      <Reference IsForward=\"false\" ReferenceType=\"HasComponent\">i=66666</Reference>\n"
"      <Reference ReferenceType=\"HasTypeDefinition\">i=63</Reference>\n"
"    </References>\n"
"    <Value>\n"
"      <uax:Int32>16000</uax:Int32>\n"
"    </Value>\n"
"  </UAVariable>\n"
"  <UAVariable BrowseName=\"1:minBel\" DataType=\"Float\" NodeId=\"i=77777\" ParentNodeId=\"i=99999\">\n"
"    <DisplayName>minBel</DisplayName>\n"
"    <Description>minBel</Description>\n"
"    <References>\n"
"      <Reference IsForward=\"false\" ReferenceType=\"HasComponent\">i=99999</Reference>\n"
"      <Reference ReferenceType=\"HasTypeDefinition\">i=63</Reference>\n"
"      <Reference ReferenceType=\"HasComponent\">i=77771</Reference>\n"
"    </References>\n"
"    <Value>\n"
"      <uax:Float>0.0</uax:Float>\n"
"    </Value>\n"
"  </UAVariable>\n"
"  <UAVariable BrowseName=\"1:AdressMinBel\" DataType=\"Int32\" NodeId=\"i=77771\" ParentNodeId=\"i=77777\">\n"
"    <DisplayName>AdressMinBel</DisplayName>\n"
"    <Description>AdressMinBel</Description>\n"
"    <References>\n"
"      <Reference IsForward=\"false\" ReferenceType=\"HasComponent\">i=77777</Reference>\n"
"      <Reference ReferenceType=\"HasTypeDefinition\">i=63</Reference>\n"
"    </References>\n"
"    <Value>\n"
"      <uax:Int32>102200</uax:Int32>\n"
"    </Value>\n"
"  </UAVariable>\n"
"  <UAMethod BrowseName=\"1:Certificate\" NodeId=\"i=509000\" ParentNodeId=\"i=99999\">\n"
"    <DisplayName>CertificateDisplayName</DisplayName>\n"
"    <Description>CertificateDescription</Description>\n"
"    <References>\n"
"      <Reference IsForward=\"false\" ReferenceType=\"HasComponent\">i=99999</Reference>\n"
"      <Reference ReferenceType=\"HasProperty\">i=20001</Reference>\n"
"      <Reference ReferenceType=\"HasProperty\">i=20002</Reference>\n"
"    </References>\n"
"  </UAMethod>\n"
"  <UAVariable BrowseName=\"0:InputArguments\" DataType=\"Argument\" NodeId=\"i=20001\" ParentNodeId=\"i=509000\" ValueRank=\"0\">\n"
"    <DisplayName>InputArguments</DisplayName>\n"
"    <Description>InputArguments</Description>\n"
"    <References>\n"
"      <Reference IsForward=\"false\" ReferenceType=\"HasProperty\">i=509000</Reference>\n"
"      <Reference ReferenceType=\"HasTypeDefinition\">i=68</Reference>\n"
"    </References>\n"
"    <Value>\n"
"      <uax:ListOfExtensionObject>\n"
"        <uax:ExtensionObject>\n"
"          <uax:TypeId>\n"
"            <uax:Identifier>i=296</uax:Identifier>\n"
"          </uax:TypeId>\n"
"          <uax:Body>\n"
"            <uax:Argument>\n"
"              <uax:Name>InputArgu</uax:Name>\n"
"              <uax:DataType>\n"
"                <uax:Identifier>i=6</uax:Identifier>\n"
"              </uax:DataType>\n"
"              <uax:ValueRank>-1</uax:ValueRank>\n"
"              <uax:ArrayDimensions />\n"
"              <uax:Description>\n"
"                <uax:Encoding>2</uax:Encoding>\n"
"                <uax:Locale />\n"
"                <uax:Text>You can upload </uax:Text>\n"
"              </uax:Description>\n"
"            </uax:Argument>\n"
"          </uax:Body>\n"
"        </uax:ExtensionObject>\n"
"      </uax:ListOfExtensionObject>\n"
"    </Value>\n"
"  </UAVariable>\n"
"  <UAVariable BrowseName=\"0:OutputArguments\" DataType=\"Argument\" NodeId=\"i=20002\" ParentNodeId=\"i=509000\" ValueRank=\"0\">\n"
"    <DisplayName>OutputArguments</DisplayName>\n"
"    <Description>OutputArguments</Description>\n"
"    <References>\n"
"      <Reference IsForward=\"false\" ReferenceType=\"HasProperty\">i=509000</Reference>\n"
"      <Reference ReferenceType=\"HasTypeDefinition\">i=68</Reference>\n"
"    </References>\n"
"    <Value>\n"
"      <uax:ListOfExtensionObject>\n"
"        <uax:ExtensionObject>\n"
"          <uax:TypeId>\n"
"            <uax:Identifier>i=296</uax:Identifier>\n"
"          </uax:TypeId>\n"
"          <uax:Body>\n"
"            <uax:Argument>\n"
"              <uax:Name>OutPutArgu</uax:Name>\n"
"              <uax:DataType>\n"
"                <uax:Identifier>i=12</uax:Identifier>\n"
"              </uax:DataType>\n"
"              <uax:ValueRank>-1</uax:ValueRank>\n"
"              <uax:ArrayDimensions />\n"
"              <uax:Description>\n"
"                <uax:Encoding>2</uax:Encoding>\n"
"                <uax:Locale />\n"
"                <uax:Text>You can see the status</uax:Text>\n"
"              </uax:Description>\n"
"            </uax:Argument>\n"
"          </uax:Body>\n"
"        </uax:ExtensionObject>\n"
"      </uax:ListOfExtensionObject>\n"
"    </Value>\n"
"  </UAVariable>\n"
"</UANodeSet>\n";



int main()
{
XMLNode node;
XMLNode_init(&node);
XMLDoc doc;
XMLDoc_init(&doc);
XMLDoc_parse_buffer_DOM(buffer, "test", &doc);
XMLNode* root = doc.nodes[doc.i_root];
char val[256];
char* p = val;
XMLNode_get_attribute_with_default(&node, "BrowseName", &p, NULL);
if (p == NULL) {
    fprintf(stderr, "BrowseName not found!\n");
} else {
    printf("BrowseName = [%s]\n", val);
}
    return 0;
}
`
