### ISSUE TITLE
Since commit 5cf1ce9 (4.3.1), XML search engine malfunctions

### ISSUE THREAD

**Issue by IgorJorobus** [matthieu-labas/sxmlc#12]
Hi Matthieu,

Looks like commit [5cf1ce9](https://github.com/matthieu-labas/sxmlc/commit/5cf1ce9460777f502f5e959992282bc919e97126) somehow breaks the search engine. It was working fine on previous commits, tested on 9fe2cdb (4.3.0) and afc5191 (4.2.10).

I'm submitting a simple XML, with the code that couldn't find a certain tag. I hope that this can help to resolve the inconvenient. Let me know if I can help out with something.

[issue_on_4_3_1.zip](https://github.com/matthieu-labas/sxmlc/files/2862703/issue_on_4_3_1.zip)

Best regards, D.

**Comment by matthieu-labas** [comment]
The macro `CHECK_NODE()` was returning on *valid* nodes, instead of *invalid* ones.
