### ISSUE TITLE
text content is not escaped

### ISSUE THREAD

**Issue by sebdel** [matthieu-labas/sxmlc#14]
Hi, it looks like html2str is not called on text content, only on attributes. Is this the expected behavior?

**Comment by matthieu-labas** [comment]
That's right. I guess I overlooked that point when I created the function.
I'll correct that...

**Comment by matthieu-labas** [comment]
Corrected in v4.5.0.

**Comment by sebdel** [comment]
Thanks. It's not in the repo yet right ? When do you plan to push it ?

**Comment by matthieu-labas** [comment]
Right, I thought I did push it but it seems to be missing. I'll check that.

**Comment by matthieu-labas** [comment]
Should be pushed now. Sorry for the delay.
