### ISSUE TITLE
Pars data from STRING 

### ISSUE THREAD

**Issue by embbo** [matthieu-labas/sxmlc#15]
Hi all, I just started sxmlc with the example and it works perfectly but I want to read an xml string NOT a file from out side..any clue how can i do that .. like this 

string xml = "<recurrence><rule><firstDayOfWeek>mo</firstDayOfWeek><repeat><daily dayFrequency=""1"" /></repeat><windowEnd>2012-10-31T10:00:00Z</windowEnd></rule></recurrence>";

Regards

**Comment by matthieu-labas** [comment]
Your XML looks strange. Are you sure you have two double-quotes `""1""` and not only one `"1"`?

Anyway, you can call any of the `XMLDoc_parse_buffer_DOM()` / `XMLDoc_parse_buffer_SAX()` functions.

**Comment by embbo** [comment]
hi sorry may be this formate is wrong .. i have simple xml string , from ethernet and i want to parse it ..

**Comment by matthieu-labas** [comment]
`XMLDoc_parse_buffer_DOM()` *does* parse string buffer.

Can you share the part that is not working? `string` is not standard C and you didn't show any code.

**Comment by matthieu-labas** [comment]
Please reopen with reproducible code so I can check.

**Comment by embbo** [comment]
hi this is the string .... 
<?xml version='1.0' encoding='utf-8'?>
<UANodeSet xmlns="http://opcfoundation.org/UA/2011/03/UANodeSet.xsd" xmlns:uax="http://opcfoundation.org/UA/2008/02/Types.xsd" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
  <NamespaceUris>
    <Uri>urx:reoag:mytestproject</Uri>
  </NamespaceUris>
  <Aliases>
    <Alias Alias="Float">i=10</Alias>
    <Alias Alias="String">i=12</Alias>
    <Alias Alias="Organizes">i=35</Alias>
    <Alias Alias="HasTypeDefinition">i=40</Alias>
    <Alias Alias="HasSubtype">i=45</Alias>
    <Alias Alias="HasComponent">i=47</Alias>
  </Aliases>
  <UAObjectType BrowseName="1:MyDevice" NodeId="ns=1;i=2001">
    <DisplayName>MyDevice</DisplayName>
    <Description>MyDevice</Description>
    <References>
      <Reference IsForward="false" ReferenceType="HasSubtype">i=58</Reference>
      <Reference ReferenceType="HasComponent">ns=1;i=2005</Reference>
    </References>
  </UAObjectType>
  <UAVariable BrowseName="1:DeviceName" DataType="String" NodeId="ns=1;i=2005" ParentNodeId="ns=1;i=2001">
    <DisplayName>DeviceName</DisplayName>
    <Description>DeviceName</Description>
    <References>
      <Reference IsForward="false" ReferenceType="HasComponent">ns=1;i=2001</Reference>
      <Reference ReferenceType="HasTypeDefinition">i=63</Reference>
    </References>
    <Value>
      <uax:String>MyName</uax:String>
    </Value>
  </UAVariable>
  <UAObject BrowseName="0:ReoVib" NodeId="i=20001" ParentNodeId="i=85">
    <DisplayName>ReoVib</DisplayName>
    <References>
      <Reference IsForward="false" ReferenceType="Organizes">i=85</Reference>
      <Reference ReferenceType="HasTypeDefinition">i=58</Reference>
      <Reference ReferenceType="HasComponent">i=62541</Reference>
      <Reference ReferenceType="HasComponent">i=62542</Reference>
      <Reference ReferenceType="HasComponent">i=20002</Reference>
      <Reference ReferenceType="HasComponent">i=55555</Reference>
      <Reference ReferenceType="HasComponent">i=20003</Reference>
      <Reference ReferenceType="HasComponent">i=20004</Reference>
      <Reference ReferenceType="HasComponent">i=20005</Reference>
      <Reference ReferenceType="HasComponent">i=20006</Reference>
      <Reference ReferenceType="HasComponent">i=20007</Reference>
      <Reference ReferenceType="HasComponent">i=20008</Reference>
      <Reference ReferenceType="HasComponent">i=20009</Reference>
      <Reference ReferenceType="HasComponent">i=20010</Reference>
      <Reference ReferenceType="HasComponent">i=20011</Reference>
      <Reference ReferenceType="HasComponent">i=20012</Reference>
      <Reference ReferenceType="HasComponent">i=20013</Reference>
      <Reference ReferenceType="HasComponent">i=20014</Reference>
      <Reference ReferenceType="HasComponent">i=20015</Reference>
      <Reference ReferenceType="HasComponent">i=20016</Reference>
      <Reference ReferenceType="HasComponent">i=20017</Reference>
      <Reference ReferenceType="HasComponent">i=20018</Reference>
      <Reference ReferenceType="HasComponent">i=20019</Reference>
      <Reference ReferenceType="HasComponent">i=20020</Reference>
      <Reference ReferenceType="HasComponent">i=20021</Reference>
    </References>
  </UAObject>
  <UAVariable BrowseName="0:ACC" DataType="Float" NodeId="i=62541" ParentNodeId="i=20001">
    <DisplayName>ACC</DisplayName>
    <Description>ACC</Description>
    <References>
      <Reference IsForward="false" ReferenceType="HasComponent">i=20001</Reference>
      <Reference ReferenceType="HasTypeDefinition">i=63</Reference>
    </References>
    <Value>
      <uax:Float>0.0</uax:Float>
    </Value>
  </UAVariable>
  <UAVariable BrowseName="0:Acel" DataType="Float" NodeId="i=62542" ParentNodeId="i=20001">
    <DisplayName>Acel</DisplayName>
    <Description>Acel</Description>
    <References>
      <Reference IsForward="false" ReferenceType="HasComponent">i=20001</Reference>
      <Reference ReferenceType="HasTypeDefinition">i=63</Reference>
    </References>
    <Value>
      <uax:Float>0.0</uax:Float>
    </Value>
  </UAVariable>
  <UAVariable BrowseName="0:timeup" DataType="Float" NodeId="i=20002" ParentNodeId="i=20001">
    <DisplayName>timeup</DisplayName>
    <Description>timeup</Description>
    <References>
      <Reference IsForward="false" ReferenceType="HasComponent">i=20001</Reference>
      <Reference ReferenceType="HasTypeDefinition">i=63</Reference>
    </References>
    <Value>
      <uax:Float>0.0</uax:Float>
    </Value>
  </UAVariable>
  <UAMethod BrowseName="0:settings" NodeId="i=55555" ParentNodeId="i=20001">
    <DisplayName>settings</DisplayName>
    <Description>settings</Description>
    <References>
      <Reference IsForward="false" ReferenceType="HasComponent">i=20001</Reference>
    </References>
  </UAMethod>
  <UAVariable BrowseName="0:NoName" DataType="Float" NodeId="i=20003" ParentNodeId="i=20001">
    <DisplayName>NoName</DisplayName>
    <Description>NoName</Description>
    <References>
      <Reference IsForward="false" ReferenceType="HasComponent">i=20001</Reference>
      <Reference ReferenceType="HasTypeDefinition">i=63</Reference>
    </References>
    <Value>
      <uax:Float>0.0</uax:Float>
    </Value>
  </UAVariable>
  <UAObject BrowseName="0:NoName" NodeId="i=20004" ParentNodeId="i=20001">
    <DisplayName>NoName</DisplayName>
    <References>
      <Reference IsForward="false" ReferenceType="HasComponent">i=20001</Reference>
      <Reference ReferenceType="HasTypeDefinition">i=58</Reference>
    </References>
  </UAObject>
  <UAVariable BrowseName="0:NoName" DataType="Float" NodeId="i=20005" ParentNodeId="i=20001">
    <DisplayName>NoName</DisplayName>
    <Description>NoName</Description>
    <References>
      <Reference IsForward="false" ReferenceType="HasComponent">i=20001</Reference>
      <Reference ReferenceType="HasTypeDefinition">i=63</Reference>
    </References>
    <Value>
      <uax:Float>0.0</uax:Float>
    </Value>
  </UAVariable>
  <UAVariable BrowseName="0:NoName" DataType="Float" NodeId="i=20006" ParentNodeId="i=20001">
    <DisplayName>NoName</DisplayName>
    <Description>NoName</Description>
    <References>
      <Reference IsForward="false" ReferenceType="HasComponent">i=20001</Reference>
      <Reference ReferenceType="HasTypeDefinition">i=63</Reference>
    </References>
    <Value>
      <uax:Float>0.0</uax:Float>
    </Value>
  </UAVariable>
  <UAVariable BrowseName="0:NoName" DataType="Float" NodeId="i=20007" ParentNodeId="i=20001">
    <DisplayName>NoName</DisplayName>
    <Description>NoName</Description>
    <References>
      <Reference IsForward="false" ReferenceType="HasComponent">i=20001</Reference>
      <Reference ReferenceType="HasTypeDefinition">i=63</Reference>
    </References>
    <Value>
      <uax:Float>0.0</uax:Float>
    </Value>
  </UAVariable>
  <UAVariable BrowseName="0:NoName" DataType="Float" NodeId="i=20008" ParentNodeId="i=20001">
    <DisplayName>NoName</DisplayName>
    <Description>NoName</Description>
    <References>
      <Reference IsForward="false" ReferenceType="HasComponent">i=20001</Reference>
      <Reference ReferenceType="HasTypeDefinition">i=63</Reference>
    </References>
    <Value>
      <uax:Float>0.0</uax:Float>
    </Value>
  </UAVariable>
  <UAVariable BrowseName="0:NoName" DataType="Float" NodeId="i=20009" ParentNodeId="i=20001">
    <DisplayName>NoName</DisplayName>
    <Description>NoName</Description>
    <References>
      <Reference IsForward="false" ReferenceType="HasComponent">i=20001</Reference>
      <Reference ReferenceType="HasTypeDefinition">i=63</Reference>
    </References>
    <Value>
      <uax:Float>0.0</uax:Float>
    </Value>
  </UAVariable>
  <UAVariable BrowseName="0:NoName" DataType="Float" NodeId="i=20010" ParentNodeId="i=20001">
    <DisplayName>NoName</DisplayName>
    <Description>NoName</Description>
    <References>
      <Reference IsForward="false" ReferenceType="HasComponent">i=20001</Reference>
      <Reference ReferenceType="HasTypeDefinition">i=63</Reference>
    </References>
    <Value>
      <uax:Float>0.0</uax:Float>
    </Value>
  </UAVariable>
  <UAVariable BrowseName="0:NoName" DataType="Float" NodeId="i=20011" ParentNodeId="i=20001">
    <DisplayName>NoName</DisplayName>
    <Description>NoName</Description>
    <References>
      <Reference IsForward="false" ReferenceType="HasComponent">i=20001</Reference>
      <Reference ReferenceType="HasTypeDefinition">i=63</Reference>
    </References>
    <Value>
      <uax:Float>0.0</uax:Float>
    </Value>
  </UAVariable>
  <UAVariable BrowseName="0:NoName" DataType="Float" NodeId="i=20012" ParentNodeId="i=20001">
    <DisplayName>NoName</DisplayName>
    <Description>NoName</Description>
    <References>
      <Reference IsForward="false" ReferenceType="HasComponent">i=20001</Reference>
      <Reference ReferenceType="HasTypeDefinition">i=63</Reference>
    </References>
    <Value>
      <uax:Float>0.0</uax:Float>
    </Value>
  </UAVariable>
  <UAVariable BrowseName="0:NoName" DataType="Float" NodeId="i=20013" ParentNodeId="i=20001">
    <DisplayName>NoName</DisplayName>
    <Description>NoName</Description>
    <References>
      <Reference IsForward="false" ReferenceType="HasComponent">i=20001</Reference>
      <Reference ReferenceType="HasTypeDefinition">i=63</Reference>
    </References>
    <Value>
      <uax:Float>0.0</uax:Float>
    </Value>
  </UAVariable>
  <UAVariable BrowseName="0:NoName" DataType="Float" NodeId="i=20014" ParentNodeId="i=20001">
    <DisplayName>NoName</DisplayName>
    <Description>NoName</Description>
    <References>
      <Reference IsForward="false" ReferenceType="HasComponent">i=20001</Reference>
      <Reference ReferenceType="HasTypeDefinition">i=63</Reference>
    </References>
    <Value>
      <uax:Float>0.0</uax:Float>
    </Value>
  </UAVariable>
  <UAVariable BrowseName="0:NoName" DataType="Float" NodeId="i=20015" ParentNodeId="i=20001">
    <DisplayName>NoName</DisplayName>
    <Description>NoName</Description>
    <References>
      <Reference IsForward="false" ReferenceType="HasComponent">i=20001</Reference>
      <Reference ReferenceType="HasTypeDefinition">i=63</Reference>
    </References>
    <Value>
      <uax:Float>0.0</uax:Float>
    </Value>
  </UAVariable>
  <UAVariable BrowseName="0:NoName" DataType="Float" NodeId="i=20016" ParentNodeId="i=20001">
    <DisplayName>NoName</DisplayName>
    <Description>NoName</Description>
    <References>
      <Reference IsForward="false" ReferenceType="HasComponent">i=20001</Reference>
      <Reference ReferenceType="HasTypeDefinition">i=63</Reference>
    </References>
    <Value>
      <uax:Float>0.0</uax:Float>
    </Value>
  </UAVariable>
  <UAVariable BrowseName="0:NoName" DataType="Float" NodeId="i=20017" ParentNodeId="i=20001">
    <DisplayName>NoName</DisplayName>
    <Description>NoName</Description>
    <References>
      <Reference IsForward="false" ReferenceType="HasComponent">i=/20001<Reference>
      <Reference ReferenceType="HasTypeDefinition">i=63</Reference>
    </References>
    <Value>
      <uax:Float>0.0</uax:Float>
    </Value>
  </UAVariable>
  <UAVariable BrowseName="0:NoName" DataType="Float" NodeId="i=20018" ParentNodeId="i=20001">
    <DisplayName>NoName</DisplayName>
    <Description>NoName</Description>
    <References>
      <Reference IsForward="false" ReferenceType="HasComponent">i=20001</Reference>
      <Reference ReferenceType="HasTypeDefinition">i=63</Reference>
    </References>
    <Value>
      <uax:Float>0.0</uax:Float>
    </Value>
  </UAVariable>
  <UAVariable BrowseName="0:NoName" DataType="Float" NodeId="i=20019" ParentNodeId="i=20001">
    <DisplayName>NoName</DisplayName>
    <Description>NoName</Description>
    <References>
      <Reference IsForward="false" ReferenceType="HasComponent">i=20001</Reference>
      <Reference ReferenceType="HasTypeDefinition">i=63</Reference>
    </References>
    <Value>
      <uax:Float>0.0</uax:Float>
    </Value>
  </UAVariable>
  <UAVariable BrowseName="0:NoName" DataType="Float" NodeId="i=20020" ParentNodeId="i=20001">
    <DisplayName>NoName</DisplayName>
    <Description>NoName</Description>
    <References>
      <Reference IsForward="false" ReferenceType="HasComponent">i=20001</Reference>
      <Reference ReferenceType="HasTypeDefinition">i=63</Reference>
    </References>
    <Value>
      <uax:Float>0.0</uax:Float>
    </Value>
  </UAVariable>
  <UAVariable BrowseName="0:NoName" DataType="Float" NodeId="i=20021" ParentNodeId="i=20001">
    <DisplayName>NoName</DisplayName>
    <Description>NoName</Description>
    <References>
      <Reference IsForward="false" ReferenceType="HasComponent">i=20001</Reference>
      <Reference ReferenceType="HasTypeDefinition">i=63</Reference>
    </References>
    <Value>
      <uax:Float>0.0</uax:Float>
    </Value>
  </UAVariable>
</UANodeSet>

**Comment by embbo** [comment]
`<?xml version='1.0' encoding='utf-8'?>
<UANodeSet xmlns="http://opcfoundation.org/UA/2011/03/UANodeSet.xsd" xmlns:uax="http://opcfoundation.org/UA/2008/02/Types.xsd" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
  <NamespaceUris>
    <Uri>urx:reoag:mytestproject</Uri>
  </NamespaceUris>
  <Aliases>
    <Alias Alias="Float">i=10</Alias>
    <Alias Alias="String">i=12</Alias>
    <Alias Alias="Organizes">i=35</Alias>
    <Alias Alias="HasTypeDefinition">i=40</Alias>
    <Alias Alias="HasSubtype">i=45</Alias>
    <Alias Alias="HasComponent">i=47</Alias>
  </Aliases>
  <UAObjectType BrowseName="1:MyDevice" NodeId="ns=1;i=2001">
    <DisplayName>MyDevice</DisplayName>
    <Description>MyDevice</Description>
    <References>
      <Reference IsForward="false" ReferenceType="HasSubtype">i=58</Reference>
      <Reference ReferenceType="HasComponent">ns=1;i=2005</Reference>
    </References>
  </UAObjectType>
  <UAVariable BrowseName="1:DeviceName" DataType="String" NodeId="ns=1;i=2005" ParentNodeId="ns=1;i=2001">
    <DisplayName>DeviceName</DisplayName>
    <Description>DeviceName</Description>
    <References>
      <Reference IsForward="false" ReferenceType="HasComponent">ns=1;i=2001</Reference>
      <Reference ReferenceType="HasTypeDefinition">i=63</Reference>
    </References>
    <Value>
      <uax:String>MyName</uax:String>
    </Value>
  </UAVariable>
  <UAObject BrowseName="0:ReoVib" NodeId="i=20001" ParentNodeId="i=85">
    <DisplayName>ReoVib</DisplayName>
    <References>
      <Reference IsForward="false" ReferenceType="Organizes">i=85</Reference>
      <Reference ReferenceType="HasTypeDefinition">i=58</Reference>
      <Reference ReferenceType="HasComponent">i=62541</Reference>
      <Reference ReferenceType="HasComponent">i=62542</Reference>
      <Reference ReferenceType="HasComponent">i=20002</Reference>
      <Reference ReferenceType="HasComponent">i=55555</Reference>
      <Reference ReferenceType="HasComponent">i=20003</Reference>
      <Reference ReferenceType="HasComponent">i=20004</Reference>
      <Reference ReferenceType="HasComponent">i=20005</Reference>
      <Reference ReferenceType="HasComponent">i=20006</Reference>
      <Reference ReferenceType="HasComponent">i=20007</Reference>
      <Reference ReferenceType="HasComponent">i=20008</Reference>
      <Reference ReferenceType="HasComponent">i=20009</Reference>
      <Reference ReferenceType="HasComponent">i=20010</Reference>
      <Reference ReferenceType="HasComponent">i=20011</Reference>
      <Reference ReferenceType="HasComponent">i=20012</Reference>
      <Reference ReferenceType="HasComponent">i=20013</Reference>
      <Reference ReferenceType="HasComponent">i=20014</Reference>
      <Reference ReferenceType="HasComponent">i=20015</Reference>
      <Reference ReferenceType="HasComponent">i=20016</Reference>
      <Reference ReferenceType="HasComponent">i=20017</Reference>
      <Reference ReferenceType="HasComponent">i=20018</Reference>
      <Reference ReferenceType="HasComponent">i=20019</Reference>
      <Reference ReferenceType="HasComponent">i=20020</Reference>
      <Reference ReferenceType="HasComponent">i=20021</Reference>
    </References>
  </UAObject>
  <UAVariable BrowseName="0:ACC" DataType="Float" NodeId="i=62541" ParentNodeId="i=20001">
    <DisplayName>ACC</DisplayName>
    <Description>ACC</Description>
    <References>
      <Reference IsForward="false" ReferenceType="HasComponent">i=20001</Reference>
      <Reference ReferenceType="HasTypeDefinition">i=63</Reference>
    </References>
    <Value>
      <uax:Float>0.0</uax:Float>
    </Value>
  </UAVariable>
  <UAVariable BrowseName="0:Acel" DataType="Float" NodeId="i=62542" ParentNodeId="i=20001">
    <DisplayName>Acel</DisplayName>
    <Description>Acel</Description>
    <References>
      <Reference IsForward="false" ReferenceType="HasComponent">i=20001</Reference>
      <Reference ReferenceType="HasTypeDefinition">i=63</Reference>
    </References>
    <Value>
      <uax:Float>0.0</uax:Float>
    </Value>
  </UAVariable>
  <UAVariable BrowseName="0:timeup" DataType="Float" NodeId="i=20002" ParentNodeId="i=20001">
    <DisplayName>timeup</DisplayName>
    <Description>timeup</Description>
    <References>
      <Reference IsForward="false" ReferenceType="HasComponent">i=20001</Reference>
      <Reference ReferenceType="HasTypeDefinition">i=63</Reference>
    </References>
    <Value>
      <uax:Float>0.0</uax:Float>
    </Value>
  </UAVariable>
  <UAMethod BrowseName="0:settings" NodeId="i=55555" ParentNodeId="i=20001">
    <DisplayName>settings</DisplayName>
    <Description>settings</Description>
    <References>
      <Reference IsForward="false" ReferenceType="HasComponent">i=20001</Reference>
    </References>
  </UAMethod>
  <UAVariable BrowseName="0:NoName" DataType="Float" NodeId="i=20003" ParentNodeId="i=20001">
    <DisplayName>NoName</DisplayName>
    <Description>NoName</Description>
    <References>
      <Reference IsForward="false" ReferenceType="HasComponent">i=20001</Reference>
      <Reference ReferenceType="HasTypeDefinition">i=63</Reference>
    </References>
    <Value>
      <uax:Float>0.0</uax:Float>
    </Value>
  </UAVariable>
  <UAObject BrowseName="0:NoName" NodeId="i=20004" ParentNodeId="i=20001">
    <DisplayName>NoName</DisplayName>
    <References>
      <Reference IsForward="false" ReferenceType="HasComponent">i=20001</Reference>
      <Reference ReferenceType="HasTypeDefinition">i=58</Reference>
    </References>
  </UAObject>
  <UAVariable BrowseName="0:NoName" DataType="Float" NodeId="i=20005" ParentNodeId="i=20001">
    <DisplayName>NoName</DisplayName>
    <Description>NoName</Description>
    <References>
      <Reference IsForward="false" ReferenceType="HasComponent">i=20001</Reference>
      <Reference ReferenceType="HasTypeDefinition">i=63</Reference>
    </References>
    <Value>
      <uax:Float>0.0</uax:Float>
    </Value>
  </UAVariable>
  <UAVariable BrowseName="0:NoName" DataType="Float" NodeId="i=20006" ParentNodeId="i=20001">
    <DisplayName>NoName</DisplayName>
    <Description>NoName</Description>
    <References>
      <Reference IsForward="false" ReferenceType="HasComponent">i=20001</Reference>
      <Reference ReferenceType="HasTypeDefinition">i=63</Reference>
    </References>
    <Value>
      <uax:Float>0.0</uax:Float>
    </Value>
  </UAVariable>
  <UAVariable BrowseName="0:NoName" DataType="Float" NodeId="i=20007" ParentNodeId="i=20001">
    <DisplayName>NoName</DisplayName>
    <Description>NoName</Description>
    <References>
      <Reference IsForward="false" ReferenceType="HasComponent">i=20001</Reference>
      <Reference ReferenceType="HasTypeDefinition">i=63</Reference>
    </References>
    <Value>
      <uax:Float>0.0</uax:Float>
    </Value>
  </UAVariable>
  <UAVariable BrowseName="0:NoName" DataType="Float" NodeId="i=20008" ParentNodeId="i=20001">
    <DisplayName>NoName</DisplayName>
    <Description>NoName</Description>
    <References>
      <Reference IsForward="false" ReferenceType="HasComponent">i=20001</Reference>
      <Reference ReferenceType="HasTypeDefinition">i=63</Reference>
    </References>
    <Value>
      <uax:Float>0.0</uax:Float>
    </Value>
  </UAVariable>
  <UAVariable BrowseName="0:NoName" DataType="Float" NodeId="i=20009" ParentNodeId="i=20001">
    <DisplayName>NoName</DisplayName>
    <Description>NoName</Description>
    <References>
      <Reference IsForward="false" ReferenceType="HasComponent">i=20001</Reference>
      <Reference ReferenceType="HasTypeDefinition">i=63</Reference>
    </References>
    <Value>
      <uax:Float>0.0</uax:Float>
    </Value>
  </UAVariable>
  <UAVariable BrowseName="0:NoName" DataType="Float" NodeId="i=20010" ParentNodeId="i=20001">
    <DisplayName>NoName</DisplayName>
    <Description>NoName</Description>
    <References>
      <Reference IsForward="false" ReferenceType="HasComponent">i=20001</Reference>
      <Reference ReferenceType="HasTypeDefinition">i=63</Reference>
    </References>
    <Value>
      <uax:Float>0.0</uax:Float>
    </Value>
  </UAVariable>
  <UAVariable BrowseName="0:NoName" DataType="Float" NodeId="i=20011" ParentNodeId="i=20001">
    <DisplayName>NoName</DisplayName>
    <Description>NoName</Description>
    <References>
      <Reference IsForward="false" ReferenceType="HasComponent">i=20001</Reference>
      <Reference ReferenceType="HasTypeDefinition">i=63</Reference>
    </References>
    <Value>
      <uax:Float>0.0</uax:Float>
    </Value>
  </UAVariable>
  <UAVariable BrowseName="0:NoName" DataType="Float" NodeId="i=20012" ParentNodeId="i=20001">
    <DisplayName>NoName</DisplayName>
    <Description>NoName</Description>
    <References>
      <Reference IsForward="false" ReferenceType="HasComponent">i=20001</Reference>
      <Reference ReferenceType="HasTypeDefinition">i=63</Reference>
    </References>
    <Value>
      <uax:Float>0.0</uax:Float>
    </Value>
  </UAVariable>
  <UAVariable BrowseName="0:NoName" DataType="Float" NodeId="i=20013" ParentNodeId="i=20001">
    <DisplayName>NoName</DisplayName>
    <Description>NoName</Description>
    <References>
      <Reference IsForward="false" ReferenceType="HasComponent">i=20001</Reference>
      <Reference ReferenceType="HasTypeDefinition">i=63</Reference>
    </References>
    <Value>
      <uax:Float>0.0</uax:Float>
    </Value>
  </UAVariable>
  <UAVariable BrowseName="0:NoName" DataType="Float" NodeId="i=20014" ParentNodeId="i=20001">
    <DisplayName>NoName</DisplayName>
    <Description>NoName</Description>
    <References>
      <Reference IsForward="false" ReferenceType="HasComponent">i=20001</Reference>
      <Reference ReferenceType="HasTypeDefinition">i=63</Reference>
    </References>
    <Value>
      <uax:Float>0.0</uax:Float>
    </Value>
  </UAVariable>
  <UAVariable BrowseName="0:NoName" DataType="Float" NodeId="i=20015" ParentNodeId="i=20001">
    <DisplayName>NoName</DisplayName>
    <Description>NoName</Description>
    <References>
      <Reference IsForward="false" ReferenceType="HasComponent">i=20001</Reference>
      <Reference ReferenceType="HasTypeDefinition">i=63</Reference>
    </References>
    <Value>
      <uax:Float>0.0</uax:Float>
    </Value>
  </UAVariable>
  <UAVariable BrowseName="0:NoName" DataType="Float" NodeId="i=20016" ParentNodeId="i=20001">
    <DisplayName>NoName</DisplayName>
    <Description>NoName</Description>
    <References>
      <Reference IsForward="false" ReferenceType="HasComponent">i=20001</Reference>
      <Reference ReferenceType="HasTypeDefinition">i=63</Reference>
    </References>
    <Value>
      <uax:Float>0.0</uax:Float>
    </Value>
  </UAVariable>
  <UAVariable BrowseName="0:NoName" DataType="Float" NodeId="i=20017" ParentNodeId="i=20001">
    <DisplayName>NoName</DisplayName>
    <Description>NoName</Description>
    <References>
      <Reference IsForward="false" ReferenceType="HasComponent">i=/20001<Reference>
      <Reference ReferenceType="HasTypeDefinition">i=63</Reference>
    </References>
    <Value>
      <uax:Float>0.0</uax:Float>
    </Value>
  </UAVariable>
  <UAVariable BrowseName="0:NoName" DataType="Float" NodeId="i=20018" ParentNodeId="i=20001">
    <DisplayName>NoName</DisplayName>
    <Description>NoName</Description>
    <References>
      <Reference IsForward="false" ReferenceType="HasComponent">i=20001</Reference>
      <Reference ReferenceType="HasTypeDefinition">i=63</Reference>
    </References>
    <Value>
      <uax:Float>0.0</uax:Float>
    </Value>
  </UAVariable>
  <UAVariable BrowseName="0:NoName" DataType="Float" NodeId="i=20019" ParentNodeId="i=20001">
    <DisplayName>NoName</DisplayName>
    <Description>NoName</Description>
    <References>
      <Reference IsForward="false" ReferenceType="HasComponent">i=20001</Reference>
      <Reference ReferenceType="HasTypeDefinition">i=63</Reference>
    </References>
    <Value>
      <uax:Float>0.0</uax:Float>
    </Value>
  </UAVariable>
  <UAVariable BrowseName="0:NoName" DataType="Float" NodeId="i=20020" ParentNodeId="i=20001">
    <DisplayName>NoName</DisplayName>
    <Description>NoName</Description>
    <References>
      <Reference IsForward="false" ReferenceType="HasComponent">i=20001</Reference>
      <Reference ReferenceType="HasTypeDefinition">i=63</Reference>
    </References>
    <Value>
      <uax:Float>0.0</uax:Float>
    </Value>
  </UAVariable>
  <UAVariable BrowseName="0:NoName" DataType="Float" NodeId="i=20021" ParentNodeId="i=20001">
    <DisplayName>NoName</DisplayName>
    <Description>NoName</Description>
    <References>
      <Reference IsForward="false" ReferenceType="HasComponent">i=20001</Reference>
      <Reference ReferenceType="HasTypeDefinition">i=63</Reference>
    </References>
    <Value>
      <uax:Float>0.0</uax:Float>
    </Value>
  </UAVariable>
</UANodeSet>
`

**Comment by embbo** [comment]
hi this is the string

**Comment by matthieu-labas** [comment]
OK thanks. Now what's the problem? What is the error? What is the code you used to parse it?
Please give the full code that shows the error. I have no idea about what is "not working"...

**Comment by embbo** [comment]
oka.. error is i am trying to parse on micro controler stm 32 .. it works okay if ,i parse for any smal part of  string but not if i load this whole file...

**Comment by embbo** [comment]
i have feeling , it can't parse this kind of xml (may be i am wrong ) string or i have change my string ..

**Comment by matthieu-labas** [comment]
Please *show me some code*!

**Comment by matthieu-labas** [comment]
STM32 typically have very little memory so you might get out-of-memory error. Are you parsing DOM? SAX?

**Comment by matthieu-labas** [comment]
Your XML is malformed btw: it has a `</References>` instead of a `</Reference>`.

**Comment by embbo** [comment]
i am parsing DOM 
Okay let me try SAX..and come back to you  but some other long strings work fine ...

**Comment by embbo** [comment]
i genrated this xml from a software ... it works fine when compy paste a small part

**Comment by matthieu-labas** [comment]
OK. Eagerly waiting for some code please...

**Comment by embbo** [comment]
char buffer[] = "<References><Reference IsForward=\"false\" ReferenceType=\"HasComponent\">ns=1;i=2003</Reference><Reference ReferenceType=\"HasTypeDefinition\">i=63</Reference></References>";
	XMLDoc_parse_buffer_DOM_text_as_nodes(buffer, "test1", &doc,0);
	//XMLDoc_parse_buffer_DOM(inputStr->data, "test1", &doc);
	XMLNode *root;
	root = doc.nodes[doc.i_root];

	char* root_name = (char*)malloc(strlen(root->tag));
	strcpy(root_name, root->tag);
	root_name[0] -= 'a' - 'A';
	//	for (int i = 0; i < root->n_children; i++)
	//	printf("%s\n", root->children[i]->father->tag);

	display_recursive_children_content(root, root->n_children, root_name);
	free(root_name);

`void display_recursive_children_content(XMLNode* source, int children_count, char* names) {

	for (int i = 0; i < children_count; i++)
    {
		XMLNode *child = source->children[i];

		int new_children = child->n_children;

		if (new_children > 0)
        {

			UA_String *s;
		//	char s[100];
			if (child->n_attributes == 0)
			{
				strcat(names, " ");
				strcat(names, child->tag);
			}
			else
			{
				for (int j = 0; j < child->n_attributes; j++)
				{
					strcpy(s->data, names);
					strcat(s->data, " ");
					strcat(s->data, child->attributes[j].name);
					strcat(s->data, ": ");
					strcat(s->data, child->attributes[j].value);
				}
			}

			display_recursive_children_content(child, new_children, s);
		}
		else
            {
			xprintf("\n%s", names);
			xprintf(" %s", child->tag);
			xprintf(": %s", child->text);


		}
	}
}`

**Comment by matthieu-labas** [comment]
The code doesn't compile: `char buffer[] = "<Reference IsForward="false" ReferenceType="HasComponent">ns=1;i=2003<Reference ReferenceType="HasTypeDefinition">i=63";` doesn't escape quotes. Besides, there is no closing tags `</Reference>`.

**Comment by embbo** [comment]
but i can retrive data and it worsk fine ..problem comes when i used that long xml strinng. posted above <?xml version='1.0'........................

**Comment by embbo** [comment]
this is the result of ...

2eferences Reference: ns=1;i=2003
2eferences Reference: i=63

<References><Reference IsForward=\"false\" ReferenceType=\"HasComponent\">ns=1;i=2003</Reference><Reference ReferenceType=\"HasTypeDefinition\">i=63</Reference></References>"

**Comment by embbo** [comment]
@matthieu-labas ... I Have question .. 
I am able to parse C string type data ..  e.g like this
 **<UAVariable BrowseName=\"0:testNode\" DataType=\"NormalizedString\" NodeId=\"i=20020\" ParentNodeId=\"ns=1;i=61234\">\n"**

	XMLDoc_parse_buffer_DOM(buffer, "test1", &doc);
	XMLNode* root;
	root = doc.nodes[doc.i_root];

But when treid to parse this type of string  which is smimpe xml string wthout "\" .I have  saved this in EEPROM and can read data from there but here it gives error.. it breaks    root = doc.nodes[doc.i_root];

 **<UAVariable BrowseName="0:testNode" DataType="NormalizedString" NodeId="i=20020" ParentNodeId="ns=1;i=61234">**


both xml files are same but 1 is with \ stored in char buffer[] and 2nd I read from internal storage

**Comment by matthieu-labas** [comment]
@embbo please create new issues for new problems: the issue system is not a forum.
In the issue, please include **code that compiles** and tell precisely how you expected it to behave; I can't spend time guessing...
