### ISSUE TITLE
search specific data in string .. key --> value

### ISSUE THREAD

**Issue by embbo** [matthieu-labas/sxmlc#16]
@matthieu-labas  
I am trying to find specific data from xml string, I tried myself but i faild . do you have any idea or clue how can I do that .. 
for example I have this string ...

`<UAVariable BrowseName="1:DeviceName" DataType="String" NodeId="ns=1;i=2005" ParentNodeId="ns=1;i=2001">
    <DisplayName>DeviceName</DisplayName>
    <Description>DeviceName</Description>
    <References>
      <Reference IsForward="false" ReferenceType="HasComponent">ns=1;i=2001</Reference>
      <Reference ReferenceType="HasTypeDefinition">i=63</Reference>
    </References>
    <Value>
      <uax:String>MyName</uax:String>
    </Value>
  </UAVariable>`

I can read this sting but I want to read values of  BrowseName, DataType, NodeId .... which are 1:DeviceName ..String and ns=1;i=2005 repectively 

Like Key --> value

**Comment by matthieu-labas** [comment]
If you already have a reference to the `XMLNode`, you can just call `XMLNode_get_attribute()`:

```
XMLNode* node = ...;
char val[256];
if (XMLNode_get_attribute(node, "BrowseName", &val) && val[0]) {
    // Process "BrowseName" value in val
}
```

Note that `XMLNode_get_attribute()` will return an empty string `""` if the attribute doesn't exist. You should use `XMLNode_get_attribute_with_default()` to return something else (e.g. `NULL`):


```
XMLNode* node = ...;
char val[256];
char* p = val; // p points to memory that will be filled with the attribute value if found (i.e. "val" buffer), or will be set to NULL if the attribute is not found
if (XMLNode_get_attribute_with_default(node, "BrowseName", &p, NULL) && p != NULL) {
    // Process "BrowseName" value in val
}
```

**Comment by embbo** [comment]
`XMLNode* node;
    XMLNode_init(&node);
char val[256];
    char* q = val; 
    if (XMLNode_get_attribute_with_default(&node, "BrowseName", &q, NULL) && q != NULL) {
        // Process "BrowseName" value in val
        sx_printf(C2SX("'value' [%s]\n"), val);
    }`

Hi can you check if I am doing okay..

**Comment by matthieu-labas** [comment]
Remove the `*` in `XMLNode* node` so calls to `XMLNode_init(&node)` can *compile without warning*.

You can try something like:
```
const char* xmlstr = "<your XML string>";
XMLDoc doc;
XMLDoc_init(&doc);
XMLDoc_parse_buffer_DOM(xmlstr, "test", &doc);
XMLNode* root = doc.nodes[doc.i_root];
char val[256];
char* p = val;
XMLNode_get_attribute_with_default(node, "BrowseName", &p, NULL);
if (p == NULL) {
    fprintf(stderr, "BrowseName not found!\n");
} else {
    printf("BrowseName = [%s]\n", val);
}
```

**Comment by embbo** [comment]
its doesn't look difficult but ...its doesn't work ..XMLNode_get_attribute_with_default(node, "BrowseName", &p, NULL);  always make condition true XMLNode_get_attribute always make false

**Comment by matthieu-labas** [comment]
Can you post code that I can copy-paste and compile to reproduce the problem and find a solution?

`XMLNode_get_attribute_with_default()` returns `false` when parameters are *valid* (or on memory error), not when it found the attribute. You should check for `p != NULL` to know if the attribute is found (and `p` points to its value).

**Comment by matthieu-labas** [comment]
@embbo I removed the comment you made on the wrong issue and pasted it here:

```
#include <stdio.h>
#include <stdlib.h>
#include "sxmlc.h"
#include "sxmlsearch.h"

const char *buffer = "<?xml version='1.0' encoding='utf-8'?>\n"
"<UANodeSet xmlns=\"http://opcfoundation.org/UA/2011/03/UANodeSet.xsd\" xmlns:uax=\"http://opcfoundation.org/UA/2008/02/Types.xsd\" xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\" xmlns:xsi=\"http://www.w3.org/2001/XMLSchema-instance\">\n"
"  <NamespaceUris>\n"
"    <Uri>urx:reoag:mytestproject</Uri>\n"
"  </NamespaceUris>\n"
"  <Aliases>\n"
"    <Alias Alias=\"Int32\">i=6</Alias>\n"
"    <Alias Alias=\"Float\">i=10</Alias>\n"
"    <Alias Alias=\"String\">i=12</Alias>\n"
"    <Alias Alias=\"Organizes\">i=35</Alias>\n"
"    <Alias Alias=\"HasTypeDefinition\">i=40</Alias>\n"
"    <Alias Alias=\"HasSubtype\">i=45</Alias>\n"
"    <Alias Alias=\"HasProperty\">i=46</Alias>\n"
"    <Alias Alias=\"HasComponent\">i=47</Alias>\n"
"    <Alias Alias=\"Argument\">i=296</Alias>\n"
"  </Aliases>\n"
"  <UAObjectType BrowseName=\"MyDeviceBrowseName\" NodeId=\"ns=1;i=2001\">\n"
"    <DisplayName>MyDeviceDisplayName</DisplayName>\n"
"    <Description>MyDeviceDescription</Description>\n"
"    <References>\n"
"      <Reference IsForward=\"false\" ReferenceType=\"HasSubtype\">i=58</Reference>\n"
"      <Reference ReferenceType=\"HasComponent\">ns=1;i=2005</Reference>\n"
"    </References>\n"
"  </UAObjectType>\n"
"  <UAVariable BrowseName=\"1:DeviceNameBrowseName\" DataType=\"String\" NodeId=\"ns=1;i=2005\" ParentNodeId=\"ns=1;i=2001\">\n"
"    <DisplayName>DeviceName</DisplayName>\n"
"    <Description IsEnable=\"false\" >DeviceDescription</Description>\n"
"    <References>\n"
"      <Reference IsForward=\"false\" ReferenceType=\"HasComponent\">ns=1;i=2001</Reference>\n"
"      <Reference ReferenceType=\"HasTypeDefinition\">i=63</Reference>\n"
"    </References>\n"
"    <Value>\n"
"      <uax:String>MyName</uax:String>\n"
"    </Value>\n"
"  </UAVariable>\n"
"  <UAObject BrowseName=\"1:REOVIB\" NodeId=\"i=99999\" ParentNodeId=\"i=85\">\n"
"    <DisplayName>REOVIB</DisplayName>\n"
"    <References>\n"
"      <Reference IsForward=\"false\" ReferenceType=\"Organizes\">i=85</Reference>\n"
"      <Reference ReferenceType=\"HasTypeDefinition\">i=58</Reference>\n"
"      <Reference ReferenceType=\"HasComponent\">i=66666</Reference>\n"
"      <Reference ReferenceType=\"HasComponent\">i=77777</Reference>\n"
"      <Reference ReferenceType=\"HasComponent\">i=509000</Reference>\n"
"    </References>\n"
"  </UAObject>\n"
"  <UAVariable AccessLevel=\"3\" BrowseName=\"1:minAccel\" DataType=\"Float\" NodeId=\"i=66666\" ParentNodeId=\"i=99999\" UserAccessLevel=\"3\">\n"
"    <DisplayName>DisplayNameminAccel</DisplayName>\n"
"    <Description>DescriptionminAccel</Description>\n"
"    <References>\n"
"      <Reference IsForward=\"false\" ReferenceType=\"HasComponent\">i=99999</Reference>\n"
"      <Reference ReferenceType=\"HasTypeDefinition\">i=63</Reference>\n"
"      <Reference ReferenceType=\"HasComponent\">i=66661</Reference>\n"
"    </References>\n"
"    <Value>\n"
"      <uax:Float>0.0</uax:Float>\n"
"    </Value>\n"
"  </UAVariable>\n"
"  <UAVariable BrowseName=\"1:CanAdress\" DataType=\"Int32\" NodeId=\"i=66661\" ParentNodeId=\"i=66666\">\n"
"    <DisplayName>CanAdress</DisplayName>\n"
"    <Description>CanAdressminAccel</Description>\n"
"    <References>\n"
"      <Reference IsForward=\"false\" ReferenceType=\"HasComponent\">i=66666</Reference>\n"
"      <Reference ReferenceType=\"HasTypeDefinition\">i=63</Reference>\n"
"    </References>\n"
"    <Value>\n"
"      <uax:Int32>16000</uax:Int32>\n"
"    </Value>\n"
"  </UAVariable>\n"
"  <UAVariable BrowseName=\"1:minBel\" DataType=\"Float\" NodeId=\"i=77777\" ParentNodeId=\"i=99999\">\n"
"    <DisplayName>minBel</DisplayName>\n"
"    <Description>minBel</Description>\n"
"    <References>\n"
"      <Reference IsForward=\"false\" ReferenceType=\"HasComponent\">i=99999</Reference>\n"
"      <Reference ReferenceType=\"HasTypeDefinition\">i=63</Reference>\n"
"      <Reference ReferenceType=\"HasComponent\">i=77771</Reference>\n"
"    </References>\n"
"    <Value>\n"
"      <uax:Float>0.0</uax:Float>\n"
"    </Value>\n"
"  </UAVariable>\n"
"  <UAVariable BrowseName=\"1:AdressMinBel\" DataType=\"Int32\" NodeId=\"i=77771\" ParentNodeId=\"i=77777\">\n"
"    <DisplayName>AdressMinBel</DisplayName>\n"
"    <Description>AdressMinBel</Description>\n"
"    <References>\n"
"      <Reference IsForward=\"false\" ReferenceType=\"HasComponent\">i=77777</Reference>\n"
"      <Reference ReferenceType=\"HasTypeDefinition\">i=63</Reference>\n"
"    </References>\n"
"    <Value>\n"
"      <uax:Int32>102200</uax:Int32>\n"
"    </Value>\n"
"  </UAVariable>\n"
"  <UAMethod BrowseName=\"1:Certificate\" NodeId=\"i=509000\" ParentNodeId=\"i=99999\">\n"
"    <DisplayName>CertificateDisplayName</DisplayName>\n"
"    <Description>CertificateDescription</Description>\n"
"    <References>\n"
"      <Reference IsForward=\"false\" ReferenceType=\"HasComponent\">i=99999</Reference>\n"
"      <Reference ReferenceType=\"HasProperty\">i=20001</Reference>\n"
"      <Reference ReferenceType=\"HasProperty\">i=20002</Reference>\n"
"    </References>\n"
"  </UAMethod>\n"
"  <UAVariable BrowseName=\"0:InputArguments\" DataType=\"Argument\" NodeId=\"i=20001\" ParentNodeId=\"i=509000\" ValueRank=\"0\">\n"
"    <DisplayName>InputArguments</DisplayName>\n"
"    <Description>InputArguments</Description>\n"
"    <References>\n"
"      <Reference IsForward=\"false\" ReferenceType=\"HasProperty\">i=509000</Reference>\n"
"      <Reference ReferenceType=\"HasTypeDefinition\">i=68</Reference>\n"
"    </References>\n"
"    <Value>\n"
"      <uax:ListOfExtensionObject>\n"
"        <uax:ExtensionObject>\n"
"          <uax:TypeId>\n"
"            <uax:Identifier>i=296</uax:Identifier>\n"
"          </uax:TypeId>\n"
"          <uax:Body>\n"
"            <uax:Argument>\n"
"              <uax:Name>InputArgu</uax:Name>\n"
"              <uax:DataType>\n"
"                <uax:Identifier>i=6</uax:Identifier>\n"
"              </uax:DataType>\n"
"              <uax:ValueRank>-1</uax:ValueRank>\n"
"              <uax:ArrayDimensions />\n"
"              <uax:Description>\n"
"                <uax:Encoding>2</uax:Encoding>\n"
"                <uax:Locale />\n"
"                <uax:Text>You can upload </uax:Text>\n"
"              </uax:Description>\n"
"            </uax:Argument>\n"
"          </uax:Body>\n"
"        </uax:ExtensionObject>\n"
"      </uax:ListOfExtensionObject>\n"
"    </Value>\n"
"  </UAVariable>\n"
"  <UAVariable BrowseName=\"0:OutputArguments\" DataType=\"Argument\" NodeId=\"i=20002\" ParentNodeId=\"i=509000\" ValueRank=\"0\">\n"
"    <DisplayName>OutputArguments</DisplayName>\n"
"    <Description>OutputArguments</Description>\n"
"    <References>\n"
"      <Reference IsForward=\"false\" ReferenceType=\"HasProperty\">i=509000</Reference>\n"
"      <Reference ReferenceType=\"HasTypeDefinition\">i=68</Reference>\n"
"    </References>\n"
"    <Value>\n"
"      <uax:ListOfExtensionObject>\n"
"        <uax:ExtensionObject>\n"
"          <uax:TypeId>\n"
"            <uax:Identifier>i=296</uax:Identifier>\n"
"          </uax:TypeId>\n"
"          <uax:Body>\n"
"            <uax:Argument>\n"
"              <uax:Name>OutPutArgu</uax:Name>\n"
"              <uax:DataType>\n"
"                <uax:Identifier>i=12</uax:Identifier>\n"
"              </uax:DataType>\n"
"              <uax:ValueRank>-1</uax:ValueRank>\n"
"              <uax:ArrayDimensions />\n"
"              <uax:Description>\n"
"                <uax:Encoding>2</uax:Encoding>\n"
"                <uax:Locale />\n"
"                <uax:Text>You can see the status</uax:Text>\n"
"              </uax:Description>\n"
"            </uax:Argument>\n"
"          </uax:Body>\n"
"        </uax:ExtensionObject>\n"
"      </uax:ListOfExtensionObject>\n"
"    </Value>\n"
"  </UAVariable>\n"
"</UANodeSet>\n";



int main()
{
XMLNode node;
XMLNode_init(&node);
XMLDoc doc;
XMLDoc_init(&doc);
XMLDoc_parse_buffer_DOM(buffer, "test", &doc);
XMLNode* root = doc.nodes[doc.i_root];
char val[256];
char* p = val;
XMLNode_get_attribute_with_default(&node, "BrowseName", &p, NULL);
if (p == NULL) {
    fprintf(stderr, "BrowseName not found!\n");
} else {
    printf("BrowseName = [%s]\n", val);
}
    return 0;
}
```

**Comment by embbo** [comment]
@matthieu-labas okay thnyk you .. let me know where i am doing wrong

**Comment by matthieu-labas** [comment]
The problem is that you're parsing a full XML *document* when `XMLNode_get_attribute_with_default()` works on XML *nodes*. You first need to get a reference to the proper node (manually or through search). It works with the following code:

```
const char* xmlstr = "<UAVariable BrowseName=\"1:DeviceNameBrowseName\" DataType=\"String\" NodeId=\"ns=1;i=2005\" ParentNodeId=\"ns=1;i=2001\">";

int main()
{
	XMLDoc doc;
	XMLDoc_init(&doc);
	XMLDoc_parse_buffer_DOM(xmlstr, "test", &doc);
	XMLNode* root = doc.nodes[doc.i_root];
	const char* p = NULL;
	XMLNode_get_attribute_with_default(root, "BrowseName", &p, NULL);
	if (p == NULL) {
		fprintf(stderr, "BrowseName not found!\n");
	} else {
		printf("BrowseName = [%s]\n", p);
	}
    return 0;
}
```

**Comment by embbo** [comment]
@matthieu-labas  okay got it ..thank you

**Comment by embbo** [comment]
@matthieu-labas 
 I am doing it with Xpath ..  xpath path works fine for the first Tag (//UAVariable[1]) but for the second Tag((//UAVariable[2])) , it search again first.

**Comment by matthieu-labas** [comment]
Again, please show the code I can compile to reproduce the error, and the behavior you expect.

**Comment by embbo** [comment]
@matthieu-labas ... what I am Looking is, TREE, So I can save data in C as structure of array ... can you give me the lead how can i start with sxmlc

**Comment by matthieu-labas** [comment]
Please provide some *code*. I don't know what you mean by "TREE"...

**Comment by embbo** [comment]
<UAObjectType BrowseName=\"MyDeviceBrowseName\" NodeId=\"ns=1;i=2001\">\n"
"    <DisplayName>MyDeviceDisplayName</DisplayName>\n"
"    <Description>MyDeviceDescription</Description>\n"
"    <References>\n"
"      <Reference IsForward=\"false\" ReferenceType=\"HasSubtype\">i=58</Reference>\n"
"      <Reference ReferenceType=\"HasComponent\">ns=1;i=2005</Reference>\n"
"    </References>\n"
"  </UAObjectType>\n"
"  <UAVariable BrowseName=\"1:DeviceNameBrowseName\" DataType=\"String\" NodeId=\"ns=1;i=2005\" ParentNodeId=\"ns=1;i=2001\">\n"
"    <DisplayName>DeviceName</DisplayName>\n"
"    <Description IsEnable=\"false\" >DeviceDescription</Description>\n"
"    <References>\n"
"      <Reference IsForward=\"false\" ReferenceType=\"HasComponent\">ns=1;i=2001</Reference>\n"
"      <Reference ReferenceType=\"HasTypeDefinition\">i=63</Reference>\n"
"    </References>\n"
"    <Value>\n"
"      <uax:String>MyName</uax:String>\n"
"    </Value>\n"
"  </UAVariable>\n"

I mean I want to save all attricbutes in Linked list and used them later in other fucntion .  if I have two attributes as in UAObjectType  I have tree if two but if i have more attrivutes i have tree of more attributes ..

**Comment by matthieu-labas** [comment]
I don't understand. SXMLC will give you access to node information: name, attributes names and values; no less but no more. The values you get are already allocated, meaning you need to free them, but moreover: you can keep the reference and put it in any other data structure you want: list, tree, array, ...
This is not a problem of SXMLC but of the library/program you're trying to design: parse the XML document, go through its nodes (recursively, if needed), find the attributes you want and save their values in your own data structures. Then, once finished, free all those values.

**Comment by embbo** [comment]
void display_recursive_children_content(XMLNode*source  , int children_count, char* names) {

	for (int i = 0; i < source->n_children; i++) {



		XMLNode *child = source->children[i];

		int new_children = child->n_children;

		if (new_children > 0) {
			char s[100];
			if (child->n_attributes == 0)
			{

				strcat(names, " ");
				strcat(names, child->tag);

				//printf(" n%s", names);

			//printf("  %s", child->text);
			}
			else
                 printf(" \n %s", child->tag);
				for (int j = 0; j < child->n_attributes; j++)
				{

					strcpy(s, names);
					strcat(s, " ");
					strcat(s, child->attributes[j].name);
					strcat(s, ": ");
					strcat(s, child->attributes[j].value);

					printf(" %s", child->attributes[j].name);
					printf(" %s", child->attributes[j].value);
				}

			display_recursive_children_content(child, new_children, s);
		}
		else {
			printf("   %s", names);
			printf("   %s", child->tag);
			printf("   %s", child->text);

		}
	}
}

int main()
{
    XMLDoc doc;
	XMLDoc_init(&doc);
	char buffer[] = "<?xml version='1.0' encoding='utf-8'?>\n"
"<UANodeSet xmlns=\"http://opcfoundation.org/UA/2011/03/UANodeSet.xsd\" xmlns:uax=\"http://opcfoundation.org/UA/2008/02/Types.xsd\" xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\" xmlns:xsi=\"http://www.w3.org/2001/XMLSchema-instance\">\n"

"  <UAVariable BrowseName=\"1:DeviceNameBrowseName\" DataType=\"String\" NodeId=\"ns=1;i=2005\" ParentNodeId=\"ns=1;i=2001\">\n"
"    <DisplayName>DeviceName</DisplayName>\n"
"    <Description>DeviceName</Description>\n"
"    <References>\n"
"      <Reference IsForward=\"false\" ReferenceType=\"HasComponent\">ns=1;i=2001</Reference>\n"
"      <Reference ReferenceType=\"HasTypeDefinition\">i=63</Reference>\n"
"    </References>\n"
"    <Value>\n"
"      <uax:String>MyName</uax:String>\n"
"    </Value>\n"
"  </UAVariable>\n"


"  <UAVariable AccessLevel=\"3\" BrowseName=\"1:minAccel\" DataType=\"Float\" NodeId=\"i=66666\" ParentNodeId=\"i=99999\" UserAccessLevel=\"3\">\n"
"    <DisplayName>DisplayNameminAccel</DisplayName>\n"
"    <Description>DescriptionminAccel</Description>\n"
"    <References>\n"
"      <Reference IsForward=\"false\" ReferenceType=\"HasComponent\">i=99999</Reference>\n"
"      <Reference ReferenceType=\"HasTypeDefinition\">i=63</Reference>\n"
"      <Reference ReferenceType=\"HasComponent\">i=66661</Reference>\n"
"    </References>\n"
"    <Value>\n"
"      <uax:Float>0.0</uax:Float>\n"
"    </Value>\n"
"  </UAVariable>\n"

"  <UAVariable BrowseName=\"1:CanAdress\" DataType=\"Int32\" NodeId=\"i=66661\" ParentNodeId=\"i=66666\">\n"
"    <DisplayName>CanAdress</DisplayName>\n"
"    <Description>CanAdressminAccel</Description>\n"
"    <References>\n"
"      <Reference IsForward=\"false\" ReferenceType=\"HasComponent\">i=66666</Reference>\n"
"      <Reference ReferenceType=\"HasTypeDefinition\">i=63</Reference>\n"
"    </References>\n"
"    <Value>\n"
"      <uax:Int32>16000</uax:Int32>\n"
"    </Value>\n"
"  </UAVariable>\n"

"  <UAVariable BrowseName=\"1:minBel\" DataType=\"Float\" NodeId=\"i=77777\" ParentNodeId=\"i=99999\">\n"
"    <DisplayName>minBel</DisplayName>\n"
"    <Description>minBel</Description>\n"
"    <References>\n"
"      <Reference IsForward=\"false\" ReferenceType=\"HasComponent\">i=99999</Reference>\n"
"      <Reference ReferenceType=\"HasTypeDefinition\">i=63</Reference>\n"
"      <Reference ReferenceType=\"HasComponent\">i=77771</Reference>\n"
"    </References>\n"
"    <Value>\n"
"      <uax:Float>0.0</uax:Float>\n"
"    </Value>\n"
"  </UAVariable>\n"

"  <UAVariable BrowseName=\"1:AdressMinBel\" DataType=\"Int32\" NodeId=\"i=77771\" ParentNodeId=\"i=77777\">\n"
"    <DisplayName>AdressMinBel</DisplayName>\n"
"    <Description>AdressMinBel</Description>\n"
"    <References>\n"
"      <Reference IsForward=\"false\" ReferenceType=\"HasComponent\">i=77777</Reference>\n"
"      <Reference ReferenceType=\"HasTypeDefinition\">i=63</Reference>\n"
"    </References>\n"
"    <Value>\n"
"      <uax:Int32>102200</uax:Int32>\n"
"    </Value>\n"
"  </UAVariable>\n"
"";

XMLDoc_parse_buffer_DOM(buffer, "test1", &doc);
				XMLNode *root;
				root = doc.nodes[doc.i_root];

				char* root_name = (char*)malloc(strlen(root->tag));
				strcpy(root_name, root->tag);


				       // printf("%d ",root->n_children); // number of tags
				//root_name[0] -= 'a' - 'A';
				//	for (int i = 0; i < root->n_children; i++)
				//	printf("%s\n", root->children[i]->father->tag);

				display_recursive_children_content(root, root->n_children, root_name);
				free(root_name);



	return 0;
}

**Comment by embbo** [comment]
I am using this recrsive function but I am unable to find all tags , for example i miss 
<Reference IsForward="false" ReferenceType="HasComponent">i=77777\n"
" <Reference ReferenceType="HasTypeDefinition">i=63\n"

**Comment by embbo** [comment]
why can't I find all tags.. what can be problem ..


void display_recursive_children_content(XMLNode*source  , int children_count, char* names) {

	for (int i = 0; i < source->n_children; i++) {



		XMLNode *child = source->children[i];

		int new_children = child->n_children;

		if (new_children > 0) {
			char s[100];
			if (child->n_attributes == 0)
			{

				strcat(names, " ");
				strcat(names, child->tag);

				//printf(" n%s", names);

			//printf("  %s", child->text);
			}
			else
                 printf(" \n %s", child->tag);
				for (int j = 0; j < child->n_attributes; j++)
				{

					strcpy(s, names);
					strcat(s, " ");
					strcat(s, child->attributes[j].name);
					strcat(s, ": ");
					strcat(s, child->attributes[j].value);

					printf(" %s", child->attributes[j].name);
					printf(" %s", child->attributes[j].value);
				}

			display_recursive_children_content(child, new_children, s);
		}
		else {
			printf("   %s", names);
			printf("   %s", child->tag);
			printf("   %s", child->text);

		}
	}
}

> @embbo I removed the comment you made on the wrong issue and pasted it here:
> 
> ```
> #include <stdio.h>
> #include <stdlib.h>
> #include "sxmlc.h"
> #include "sxmlsearch.h"
> 
> const char *buffer = "<?xml version='1.0' encoding='utf-8'?>\n"
> "<UANodeSet xmlns=\"http://opcfoundation.org/UA/2011/03/UANodeSet.xsd\" xmlns:uax=\"http://opcfoundation.org/UA/2008/02/Types.xsd\" xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\" xmlns:xsi=\"http://www.w3.org/2001/XMLSchema-instance\">\n"
> "  <NamespaceUris>\n"
> "    <Uri>urx:reoag:mytestproject</Uri>\n"
> "  </NamespaceUris>\n"
> "  <Aliases>\n"
> "    <Alias Alias=\"Int32\">i=6</Alias>\n"
> "    <Alias Alias=\"Float\">i=10</Alias>\n"
> "    <Alias Alias=\"String\">i=12</Alias>\n"
> "    <Alias Alias=\"Organizes\">i=35</Alias>\n"
> "    <Alias Alias=\"HasTypeDefinition\">i=40</Alias>\n"
> "    <Alias Alias=\"HasSubtype\">i=45</Alias>\n"
> "    <Alias Alias=\"HasProperty\">i=46</Alias>\n"
> "    <Alias Alias=\"HasComponent\">i=47</Alias>\n"
> "    <Alias Alias=\"Argument\">i=296</Alias>\n"
> "  </Aliases>\n"
> "  <UAObjectType BrowseName=\"MyDeviceBrowseName\" NodeId=\"ns=1;i=2001\">\n"
> "    <DisplayName>MyDeviceDisplayName</DisplayName>\n"
> "    <Description>MyDeviceDescription</Description>\n"
> "    <References>\n"
> "      <Reference IsForward=\"false\" ReferenceType=\"HasSubtype\">i=58</Reference>\n"
> "      <Reference ReferenceType=\"HasComponent\">ns=1;i=2005</Reference>\n"
> "    </References>\n"
> "  </UAObjectType>\n"
> "  <UAVariable BrowseName=\"1:DeviceNameBrowseName\" DataType=\"String\" NodeId=\"ns=1;i=2005\" ParentNodeId=\"ns=1;i=2001\">\n"
> "    <DisplayName>DeviceName</DisplayName>\n"
> "    <Description IsEnable=\"false\" >DeviceDescription</Description>\n"
> "    <References>\n"
> "      <Reference IsForward=\"false\" ReferenceType=\"HasComponent\">ns=1;i=2001</Reference>\n"
> "      <Reference ReferenceType=\"HasTypeDefinition\">i=63</Reference>\n"
> "    </References>\n"
> "    <Value>\n"
> "      <uax:String>MyName</uax:String>\n"
> "    </Value>\n"
> "  </UAVariable>\n"
> "  <UAObject BrowseName=\"1:REOVIB\" NodeId=\"i=99999\" ParentNodeId=\"i=85\">\n"
> "    <DisplayName>REOVIB</DisplayName>\n"
> "    <References>\n"
> "      <Reference IsForward=\"false\" ReferenceType=\"Organizes\">i=85</Reference>\n"
> "      <Reference ReferenceType=\"HasTypeDefinition\">i=58</Reference>\n"
> "      <Reference ReferenceType=\"HasComponent\">i=66666</Reference>\n"
> "      <Reference ReferenceType=\"HasComponent\">i=77777</Reference>\n"
> "      <Reference ReferenceType=\"HasComponent\">i=509000</Reference>\n"
> "    </References>\n"
> "  </UAObject>\n"
> "  <UAVariable AccessLevel=\"3\" BrowseName=\"1:minAccel\" DataType=\"Float\" NodeId=\"i=66666\" ParentNodeId=\"i=99999\" UserAccessLevel=\"3\">\n"
> "    <DisplayName>DisplayNameminAccel</DisplayName>\n"
> "    <Description>DescriptionminAccel</Description>\n"
> "    <References>\n"
> "      <Reference IsForward=\"false\" ReferenceType=\"HasComponent\">i=99999</Reference>\n"
> "      <Reference ReferenceType=\"HasTypeDefinition\">i=63</Reference>\n"
> "      <Reference ReferenceType=\"HasComponent\">i=66661</Reference>\n"
> "    </References>\n"
> "    <Value>\n"
> "      <uax:Float>0.0</uax:Float>\n"
> "    </Value>\n"
> "  </UAVariable>\n"
> "  <UAVariable BrowseName=\"1:CanAdress\" DataType=\"Int32\" NodeId=\"i=66661\" ParentNodeId=\"i=66666\">\n"
> "    <DisplayName>CanAdress</DisplayName>\n"
> "    <Description>CanAdressminAccel</Description>\n"
> "    <References>\n"
> "      <Reference IsForward=\"false\" ReferenceType=\"HasComponent\">i=66666</Reference>\n"
> "      <Reference ReferenceType=\"HasTypeDefinition\">i=63</Reference>\n"
> "    </References>\n"
> "    <Value>\n"
> "      <uax:Int32>16000</uax:Int32>\n"
> "    </Value>\n"
> "  </UAVariable>\n"
> "  <UAVariable BrowseName=\"1:minBel\" DataType=\"Float\" NodeId=\"i=77777\" ParentNodeId=\"i=99999\">\n"
> "    <DisplayName>minBel</DisplayName>\n"
> "    <Description>minBel</Description>\n"
> "    <References>\n"
> "      <Reference IsForward=\"false\" ReferenceType=\"HasComponent\">i=99999</Reference>\n"
> "      <Reference ReferenceType=\"HasTypeDefinition\">i=63</Reference>\n"
> "      <Reference ReferenceType=\"HasComponent\">i=77771</Reference>\n"
> "    </References>\n"
> "    <Value>\n"
> "      <uax:Float>0.0</uax:Float>\n"
> "    </Value>\n"
> "  </UAVariable>\n"
> "  <UAVariable BrowseName=\"1:AdressMinBel\" DataType=\"Int32\" NodeId=\"i=77771\" ParentNodeId=\"i=77777\">\n"
> "    <DisplayName>AdressMinBel</DisplayName>\n"
> "    <Description>AdressMinBel</Description>\n"
> "    <References>\n"
> "      <Reference IsForward=\"false\" ReferenceType=\"HasComponent\">i=77777</Reference>\n"
> "      <Reference ReferenceType=\"HasTypeDefinition\">i=63</Reference>\n"
> "    </References>\n"
> "    <Value>\n"
> "      <uax:Int32>102200</uax:Int32>\n"
> "    </Value>\n"
> "  </UAVariable>\n"
> "  <UAMethod BrowseName=\"1:Certificate\" NodeId=\"i=509000\" ParentNodeId=\"i=99999\">\n"
> "    <DisplayName>CertificateDisplayName</DisplayName>\n"
> "    <Description>CertificateDescription</Description>\n"
> "    <References>\n"
> "      <Reference IsForward=\"false\" ReferenceType=\"HasComponent\">i=99999</Reference>\n"
> "      <Reference ReferenceType=\"HasProperty\">i=20001</Reference>\n"
> "      <Reference ReferenceType=\"HasProperty\">i=20002</Reference>\n"
> "    </References>\n"
> "  </UAMethod>\n"
> "  <UAVariable BrowseName=\"0:InputArguments\" DataType=\"Argument\" NodeId=\"i=20001\" ParentNodeId=\"i=509000\" ValueRank=\"0\">\n"
> "    <DisplayName>InputArguments</DisplayName>\n"
> "    <Description>InputArguments</Description>\n"
> "    <References>\n"
> "      <Reference IsForward=\"false\" ReferenceType=\"HasProperty\">i=509000</Reference>\n"
> "      <Reference ReferenceType=\"HasTypeDefinition\">i=68</Reference>\n"
> "    </References>\n"
> "    <Value>\n"
> "      <uax:ListOfExtensionObject>\n"
> "        <uax:ExtensionObject>\n"
> "          <uax:TypeId>\n"
> "            <uax:Identifier>i=296</uax:Identifier>\n"
> "          </uax:TypeId>\n"
> "          <uax:Body>\n"
> "            <uax:Argument>\n"
> "              <uax:Name>InputArgu</uax:Name>\n"
> "              <uax:DataType>\n"
> "                <uax:Identifier>i=6</uax:Identifier>\n"
> "              </uax:DataType>\n"
> "              <uax:ValueRank>-1</uax:ValueRank>\n"
> "              <uax:ArrayDimensions />\n"
> "              <uax:Description>\n"
> "                <uax:Encoding>2</uax:Encoding>\n"
> "                <uax:Locale />\n"
> "                <uax:Text>You can upload </uax:Text>\n"
> "              </uax:Description>\n"
> "            </uax:Argument>\n"
> "          </uax:Body>\n"
> "        </uax:ExtensionObject>\n"
> "      </uax:ListOfExtensionObject>\n"
> "    </Value>\n"
> "  </UAVariable>\n"
> "  <UAVariable BrowseName=\"0:OutputArguments\" DataType=\"Argument\" NodeId=\"i=20002\" ParentNodeId=\"i=509000\" ValueRank=\"0\">\n"
> "    <DisplayName>OutputArguments</DisplayName>\n"
> "    <Description>OutputArguments</Description>\n"
> "    <References>\n"
> "      <Reference IsForward=\"false\" ReferenceType=\"HasProperty\">i=509000</Reference>\n"
> "      <Reference ReferenceType=\"HasTypeDefinition\">i=68</Reference>\n"
> "    </References>\n"
> "    <Value>\n"
> "      <uax:ListOfExtensionObject>\n"
> "        <uax:ExtensionObject>\n"
> "          <uax:TypeId>\n"
> "            <uax:Identifier>i=296</uax:Identifier>\n"
> "          </uax:TypeId>\n"
> "          <uax:Body>\n"
> "            <uax:Argument>\n"
> "              <uax:Name>OutPutArgu</uax:Name>\n"
> "              <uax:DataType>\n"
> "                <uax:Identifier>i=12</uax:Identifier>\n"
> "              </uax:DataType>\n"
> "              <uax:ValueRank>-1</uax:ValueRank>\n"
> "              <uax:ArrayDimensions />\n"
> "              <uax:Description>\n"
> "                <uax:Encoding>2</uax:Encoding>\n"
> "                <uax:Locale />\n"
> "                <uax:Text>You can see the status</uax:Text>\n"
> "              </uax:Description>\n"
> "            </uax:Argument>\n"
> "          </uax:Body>\n"
> "        </uax:ExtensionObject>\n"
> "      </uax:ListOfExtensionObject>\n"
> "    </Value>\n"
> "  </UAVariable>\n"
> "</UANodeSet>\n";
> 
> 
> 
> int main()
> {
> XMLNode node;
> XMLNode_init(&node);
> XMLDoc doc;
> XMLDoc_init(&doc);
> XMLDoc_parse_buffer_DOM(buffer, "test", &doc);
> XMLNode* root = doc.nodes[doc.i_root];
> char val[256];
> char* p = val;
> XMLNode_get_attribute_with_default(&node, "BrowseName", &p, NULL);
> if (p == NULL) {
>     fprintf(stderr, "BrowseName not found!\n");
> } else {
>     printf("BrowseName = [%s]\n", val);
> }
>     return 0;
> }
> ```

**Comment by embbo** [comment]
@matthieu-labas  for example I miss refrence is forward ..hascomponent
