### ISSUE TITLE
Memory leak in XMLSearch_free()

### ISSUE THREAD

**Issue by cliffbaumann** [matthieu-labas/sxmlc#4]
search->next is not being freed in XMLSearch_free().

	if (free_next && search->next != NULL) {
		(void)XMLSearch_free(search->next, true);
		__free(search->next);     <---- this line needs to be added
		search->next = NULL;
	}

**Comment by matthieu-labas** [comment]
Thanks, I am correcting that one (and another one) in upcomng v4.2.2.

**Comment by matthieu-labas** [comment]
Pushed v4.2.2.

**Comment by cliffbaumann** [comment]
Hi Matthieu,
Thanks for the 4.2.2 update. Here is a diff of minor changes I made for my compiler warnings/errors. The first on in sxmlc.c should definitely be implemented.
Cheers,Cliff
cbaumann@cbaumann:~/workspace/sxmlc$ git diff
diff --git a/src/sxmlc.c b/src/sxmlc.c
index 62d5dc9..fa8d8f1 100644
--- a/src/sxmlc.c
+++ b/src/sxmlc.c
@@ -588,7 +588,7 @@ int XMLNode_remove_child(XMLNode* node, int i_child, int free_child)
                pt = NULL;
        else {
                pt = (XMLNode**)__malloc((node->n_children - 1) * sizeof(XMLNode*));
-               if (pt == NULL);
+               if (pt == NULL)^M
                        return -1;
        }
  
@@ -1939,7 +1939,7 @@ SXML_CHAR* str_unescape(SXML_CHAR* str)
 int split_left_right(SXML_CHAR* str, SXML_CHAR sep, int* l0, int* l1, int* i_sep, int* r0, int* r1, int ignore_spaces, int ignore_quotes)
 {
        int n0, n1, is;
-       SXML_CHAR quote;
+       SXML_CHAR quote = '\0';^M
  
        if (str == NULL)
                return false;
@@ -2264,4 +2264,6 @@ int regstrcmp(SXML_CHAR* str, SXML_CHAR* pattern)
                                break;
                }
        }
+^M
+       return 0;^M
 }
diff --git a/src/sxmlc.h b/src/sxmlc.h
index e27d538..ddd9c9f 100644
--- a/src/sxmlc.h
+++ b/src/sxmlc.h
@@ -81,7 +81,7 @@ extern "C" {
        #define sx_sprintf sprintf
        #define sx_fgetc fgetc
        #define sx_fputc fputc
-       #define sx_isspace isspace
+       #define sx_isspace(ch) isspace((int)ch)^M
        #define sx_fopen fopen
        #define sx_fclose fclose
 #endif
@@ -219,7 +219,7 @@ typedef struct _XMLDoc {
  Return tag index in user tags table when successful, or '-1' if the 'tag_type' is invalid or
  the new tag could not be registered (e.g. when 'start' does not start with '<' or 'end' does not end with '>').
  */
-int XML_register_user_tag(int tag_type, SXML_CHAR* start, SXML_CHAR* end);
+int XML_register_user_tag(TagType tag_type, SXML_CHAR* start, SXML_CHAR* end);^M
  
 /*
  Remove a registered user tag.
@@ -400,7 +400,7 @@ int XML_parse_attribute_to(const SXML_CHAR* str, int to, XMLAttribute* xmlattr);
  Fills the 'xmlnode' structure with the tag name and its attributes.
  Returns 0 if an error occurred (malformed 'str' or memory). 'TAG_*' when string is recognized.
  */
-TagType XML_parse_1string(SXML_CHAR* str, XMLNode* xmlnode);
+TagType XML_parse_1string(const SXML_CHAR* str, XMLNode* xmlnode);^M
  
 /*
  Allocate and initialize XML nodes.
 

    On Sunday, March 20, 2016 11:00 AM, Matthieu Labas <notifications@github.com> wrote:
 

 Thanks, I am correcting that one (and another one) in upcomng v4.2.2.—

**Comment by matthieu-labas** [comment]
Ouch, the never-ending Windows/Linux line-ending problem... I'm not
sure how to cope with that one. My files on Windows *all* show CR-LF,
but your diff shows only a couple lines affected. I have Git set up
with "auto crlf", I thought it should have been handled properly.
Can you attach your corrected files? I'll see how I can include them
in the next push.
Thank you, again.

Cheers, Matthieu

**Comment by cliffbaumann** [comment]
Sure. I attached them. I did a git clone on the head before modifying them this morning. 

    On Monday, March 21, 2016 10:18 AM, Matthieu Labas <notifications@github.com> wrote:
 

 Ouch, the never-ending Windows/Linux line-ending problem... I'm not
sure how to cope with that one. My files on Windows *all* show CR-LF,
but your diff shows only a couple lines affected. I have Git set up
with "auto crlf", I thought it should have been handled properly.
Can you attach your corrected files? I'll see how I can include them
in the next push.
Thank you, again.

Cheers, Matthieu

**Comment by matthieu-labas** [comment]
I can't seem to find your attachements. Did I miss something?

**Comment by cliffbaumann** [comment]
hmmmm, weird, here they are again....sxmlc.c and sxmlc.h 

    On Monday, March 21, 2016 10:35 AM, Matthieu Labas <notifications@github.com> wrote:
 

 I can't seem to find your attachements. Did I miss something?—

**Comment by matthieu-labas** [comment]
Nope, still nothing on the thread...
Can you make one last try on matthieu.labas@gmail.com? I think it will be simpler...

**Comment by cliffbaumann** [comment]
I added a pull request https://github.com/matthieu-labas/sxmlc/pull/5 

    On Monday, March 21, 2016 10:39 AM, Matthieu Labas <notifications@github.com> wrote:
 

 Nope, still nothing on the thread...
Can you make one last try on matthieu.labas@gmail.com? I think it will be simpler...—

**Comment by matthieu-labas** [comment]
Yes, I merged it, thank you. I also misunderstood the errors, I thought it was line-ending...

**Comment by cliffbaumann** [comment]
Great. This library is perfect for my application.
Thank you so much for making it public!Cliff


    On Monday, March 21, 2016 10:58 AM, Matthieu Labas <notifications@github.com> wrote:
 

 Yes, I merged it, thank you. I also misunderstood the errors, I thought it was line-ending...—
