### ISSUE TITLE
Feature request: can we have support for XMLNode_add_sibling()?

### ISSUE THREAD

**Issue by IgorJorobus** [matthieu-labas/sxmlc#9]
Hello Matthieu,

 First of all thanks for this library. It look very good for reading existing XML, and creating XML documents from scratch.

 There's some lack of support for modifying existing (loaded) XML documents. There's only one method to add a node, which is XMLNode_add_child(). This is fine when creating XML documents from scratch, but sometimes you need to add a node next to another one, right in that position, not at the end of all the children nodes of the father.

 Have you ever thought about this feature? Can we expect to have it in a near future? Is there any current workaround to bypass this?

 Thanks in advance. Best regards.

**Comment by matthieu-labas** [comment]
Good idea! I will implement it in the upcoming v4.3.0.

In the meantime, if you want that type of functionality, you should directly manipulate the `node->children` array (with `XMLNode_add_child()` to allocate space, then move all nodes one by one in a loop):

```
XMLNode_add_child(node, child);
memmove(node->children[i+1], node->children[i], node->n_children - i - 1);
node->children[i] = child;
```

**Comment by IgorJorobus** [comment]
This are very good news, and thanks for the explanation on the workaround.

I'll be looking forward for this new version! In the meantime, I'll make use of the workaround. Cheers!

**Comment by matthieu-labas** [comment]
I'm still polishing v4.3.0 but here is what the final `XMLNode_insert_child()` will look like, if you want to use it asap:

```
#define CHECK_NODE(node,ret) if ((node) == NULL || (node)->init_value != XML_INIT_DONE) return (ret)

int XMLNode_insert_child(XMLNode* node, XMLNode* child, int index)
{
	int i, j;

	CHECK_NODE(node, -1);

	/* We could process cases "first" and "last" in an optimized way, but we prefer readability to (micro-)optimization */
	if (index < 0) /* Before first => first */
		index = 0;
	if (index >= node->n_children) /* After last => last */
		index = node->n_children - 1;

	for (i = 0; i < node->n_children; i++) {
		if (!node->children[i]->active || index-- > 0)
			continue;
		/* Insert it here, at 'i' */
		if (_add_node(&node->children, &node->n_children, child) >= 0) {
			node->tag_type = TAG_FATHER;
			child->father = node;
			/* Erase 'child', which is the last node ('n_children' has been incremented by '_add_node()') */
			for (j = node->n_children - 1; j >= i; j--)
				node->children[j] = node->children[j-1];
			node->children[i] = child; /* Set it */
			return true;
		} else
			return false;
	}

	return false; /* Oops! */
}

```

**Comment by IgorJorobus** [comment]
This is great Matthieu, I'll be using this code these days. I'll be looking forward for 4.3.0.

**Comment by matthieu-labas** [comment]
v4.3.0 pushed.
Some more work is coming regarding documentation (tentative switching to Doxygen) and more thorough unit testing.

**Comment by IgorJorobus** [comment]
Wow, this was very fast, and I'll be using it on next days. Thanks!
